DEGREE_LABELS = {
  "accountancy": { "name": ["accountancy"], "abbr": ["bsa"] },
  "finance": { "name": ["finance"], "abbr": [] },
  "entrepreneurship": { "name": ["entrepreneurship"], "abbr": [] },
  "accounting": { "name": ["accounting"], "abbr": ["vsa"] },
  "anthropology": { "name": ["anthropology"], "abbr": [] },
  "applied physics": { "name": ["applied", "physics"], "abbr": ["bsap"] },
  "architecture": { "name": ["architecture"], "abbr": [] },
  "history": { "name": ["history"], "abbr": [] },
  "biology": { "name": ["biology"], "abbr": [] },
  "broadcast communication": { "name": ["broadcast", "communication"], "abbr": ["bsbrc"] },
  "business administration": { "name": ["business", "administration"], "abbr": ["bsba"] },
  "business management": { "name": ["business", "management"], "abbr": ["bsbm"] },
  "materials engineering": { "name": ["materials", "engineering"], "abbr": [] },
  "chemical engineering": { "name": ["chemical", "engineering"], "abbr": [] },
  "civil engineering": { "name": ["civil", "engineering"], "abbr": ["bsce"] },
  "electrical engineering": { "name": ["electrical", "engineering"], "abbr": ["bsee"] },
  "electronics engineering": { "name": ["electronics", "engineering"], "abbr": [] },
  "computer engineering": { "name": ["computer", "engineering"], "abbr": ["bscpe"] },
  "computer science": { "name": ["computer", "science"], "abbr": ["bscs"] },
  "information technology": { "name": ["information", "technology"], "abbr": ["bsit", "it"] },
  "biomedical engineering": { "name": ["biomedical", "engineering"], "abbr": [] },
  "economics": { "name": ["economics"], "abbr": [] },
  "cybersecurity": { "name": ["cybersecurity"], "abbr": [] },
  "networking": { "name": ["networking"], "abbr": [] },
  "electrical engineering": { "name": ["electrical", "engineering"], "abbr": ["bsee"] },
  "education": { "name": ["education"], "abbr": [] },
  "hotel and restaurant management": { "name": ["hotel", "and", "restaurant", "management"], "abbr": ["bshrm", "hrm"] },
  "artificial intelligence": { "name": ["artificial", "intelligence"], "abbr": [] },
  "software engineering": { "name": ["software", "engineering"], "abbr": [] },
  "industrial engineering": { "name": ["industrial", "engineering"], "abbr": ["bsie"] },
  "human resource": { "name": ["human", "resource"], "abbr": [] },
  "human resources": { "name": ["human", "resources"], "abbr": [] },
  "human resource management": { "name": ["human", "resource", "management"], "abbr": [] },
  "interior design": { "name": ["interior", "design"], "abbr": ["bsid"] },
  "office administration": { "name": ["office", "administration"], "abbr": [] },
  "operations management": { "name": ["operations", "management"], "abbr": [] },
  "project management": { "name": ["project", "management"], "abbr": [] },
  "facilities management": { "name": ["facilities", "management"], "abbr": [] },
  "mechanical engineering": { "name": ["mechanical", "engineering"], "abbr": ["bsme"] },
  "mathematics": { "name": ["mathematics"], "abbr": ["bsm"] },
  "philippine studies": { "name": ["philippine", "studies"], "abbr": ["bsps"] },
  "philosophy": { "name": ["philosophy"], "abbr": ["bsphilo"] },
  "physical education": { "name": ["physical", "education"], "abbr": ["bspe"] },
  "physics": { "name": ["physics"], "abbr": ["bsp", "physics"] },
  "political science": { "name": ["political", "science"], "abbr": ["polsci"] },
  "psychology": { "name": ["psychology"], "abbr": [] },
  "public administration": { "name": ["public", "administration"], "abbr": ["bspa"] },
  "social work": { "name": ["social", "work"], "abbr": ["bssw"] },
  "sociology": { "name": ["sociology"], "abbr": [] },
  "sport science": { "name": ["sport", "science"], "abbr": [] },
  "statistics": { "name": ["statistics"], "abbr": [] },
  "tourism management": { "name": ["tourism"], "abbr": ["bstm"] },
  "fine arts": { "name": ["fine", "arts"], "abbr": [] },
  "graphic design": { "name": ["graphic", "design"], "abbr": [] },
  "visual communication": { "name": ["visual", "communication"], "abbr": [] },
  "visual communications": { "name": ["visual", "communications"], "abbr": [] },
  "design and media": { "name": ["design", "and", "media"], "abbr": [] },
  "visual design": { "name": ["visual", "design"], "abbr": [] },
  "digital design": { "name": ["digital", "design"], "abbr": [] },
  "visual arts": { "name": ["visual", "arts"], "abbr": [] },
  "public relations": { "name": ["public", "relations"], "abbr": [] },
  "communication": { "name": ["communication"], "abbr": [] },
  "communication studies": { "name": ["communication", "studies"], "abbr": [] },
  "journalism": { "name": ["journalism"], "abbr": [] },
  "event management": { "name": ["event", "management"], "abbr": [] },
  "marketing": { "name": ["marketing"], "abbr": [] },
  "media studies": { "name": ["media", "studies"], "abbr": [] },
  "advertising": { "name": ["advertising"], "abbr": [] },
  "digital media": { "name": ["digital", "media"], "abbr": [] },
  "creative writing": { "name": ["creative", "writing"], "abbr": [] },
  "organizational communication": { "name": ["organizational", "communication"], "abbr": [] },
  "logistics management": { "name": ["logistics", "management"], "abbr": [] },
  "entertainment management": { "name": ["entertainment", "management"], "abbr": [] },
  "hospitality management": { "name": ["hospitality", "management"], "abbr": [] },
  "event production": { "name": ["event", "production"], "abbr": [] },
  "multimedia arts": { "name": ["multimedia", "arts"], "abbr": [] },
  "social science": { "name": ["social", "science"], "abbr": [] },
  "game design": { "name": ["game", "design"], "abbr": [] },
  "game development": { "name": ["game", "development"], "abbr": [] },
  "fashion design": { "name": ["fashion", "design"], "abbr": [] },
  "culinary arts": { "name": ["culinary", "arts"], "abbr": [] },
  "culinary": { "name": ["culinary"], "abbr": [] },
  "animation": { "name": ["animation"], "abbr": [] },
  "financial management": { "name": ["financial", "management"], "abbr": [] },
  "financial management": { "name": ["financial", "management"], "abbr": [] },
  "linguistics": { "name": ["linguistics"], "abbr": [] },
  "special education": { "name": ["special", "education"], "abbr": [] },
  "environmental science": { "name": ["environmental", "science"], "abbr": [] },
  "communication science": { "name": ["communication", "science"], "abbr": [] },
  "occupational therapy": { "name": ["occupational", "therapy"], "abbr": [] },
  "counseling": { "name": ["counseling"], "abbr": [] },
  "biochemistry": { "name": ["biochemistry"], "abbr": [] },
  "ecology": { "name": ["ecology"], "abbr": [] },
  "pharmacology": { "name": ["pharmacology"], "abbr": [] },
  "astrophysics": { "name": ["astrophysics"], "abbr": [] },
  "neuroscience": { "name": ["neuroscience"], "abbr": [] },
  "biotechnology": { "name": ["biotechnology"], "abbr": [] },
  "quantum physics": { "name": ["quantum", "physics"], "abbr": [] },
  "physical therapy": { "name": ["physical", "therapy"], "abbr": [] },
  "healthcare administration": { "name": ["healthcare", "administration"], "abbr": [] },
  "healthcare management": { "name": ["healthcare", "management"], "abbr": [] },
  "health science": { "name": ["health", "science"], "abbr": [] },
  "health sciences": { "name": ["health", "sciences"], "abbr": [] },
  "healthcare technology": { "name": ["healthcare", "technology"], "abbr": [] },
  "medical services": { "name": ["medical", "services"], "abbr": [] },
  "biological science": { "name": ["biological", "science"], "abbr": [] },
  "biological sciences": { "name": ["biological", "sciences"], "abbr": [] },
  "literature": { "name": ["literature"], "abbr": [] },
  "chemistry": { "name": ["chemistry"], "abbr": [] },
  "music": { "name": ["music"], "abbr": [] },
  "microbiology": { "name": ["microbiology"], "abbr": [] },
  "nutrition": { "name": ["nutrition"], "abbr": [] },
  "genetics": { "name": ["genetics"], "abbr": [] },
  "physiology": { "name": ["physiology"], "abbr": [] },
  "nursing": { "name": ["nursing"], "abbr": [] },
  "medical technology": { "name": ["medical", "technology"], "abbr": [] },
  "energy science": { "name": ["energy", "science"], "abbr": [] },
  "biomedical science": { "name": ["biomedical", "science"], "abbr": [] },
  "biomedical sciences": {'name': ['biomedical', 'sciences'], 'abbr': []},
  "medicine": { "name": ["medicine"], "abbr": [] },
  "dentistry": { "name": ["dentistry"], "abbr": [] },
  "pharmacy": { "name": ["pharmacy"], "abbr": [] },
  "histology": { "name": ["histology"], "abbr": [] },
  "genetics": { "name": ["genetics"], "abbr": [] },
  "robotics": { "name": ["robotics"], "abbr": [] },
  "bioinformatics": { "name": ["bioinformatics"], "abbr": [] },
  "data science": { "name": ["data", "science"], "abbr": [] },
  "clinical research": {'name': ['clinical', 'research'], 'abbr': []},
  "public health": {'name': ['public', 'health'], 'abbr': []},
  "clinical studies": {'name': ['clinical', 'studies'], 'abbr': []},
  "life sciences": {'name': ['life', 'sciences'], 'abbr': []},
  "laboratory technology": {'name': ['laboratory', 'technology'], 'abbr': []},
  "medical imaging": {'name': ['medical', 'imaging'], 'abbr': []},
  "regulatory affairs": {'name': ['regulatory', 'affairs'], 'abbr': []},
  "healthcare studies": {'name': ['healthcare', 'studies'], 'abbr': []},
  "healthcare science": {'name': ['healthcare', 'science'], 'abbr': []},
  "laboratory science": {'name': ['laboratory', 'science'], 'abbr': []},
  "laboratory sciences": {'name': ['laboratory', 'sciences'], 'abbr': []},
}
