DEGREE_LABELS = {
  "accountancy": { "name": ["accountancy"], "abbr": ["bsa"] },
  "anthropology": { "name": ["anthropology"], "abbr": [] },
  "applied physics": { "name": ["applied", "physics"], "abbr": ["bsap"] },
  "architecture": { "name": ["architecture"], "abbr": [] },
  "history": { "name": ["history"], "abbr": [] },
  "biology": { "name": ["biology"], "abbr": [] },
  "broadcast communication": { "name": ["broadcast", "communication"], "abbr": ["bsbrc"] },
  "business administration": { "name": ["business", "administration"], "abbr": ["bsba"] },
  "business management": { "name": ["business", "management"], "abbr": ["bsbm"] },
  "chemical engineering": { "name": ["chemical", "engineering"], "abbr": [] },
  "civil engineering": { "name": ["civil", "engineering"], "abbr": ["bsce"] },
  "computer engineering": { "name": ["computer", "engineering"], "abbr": ["bscpe"] },
  "computer science": { "name": ["computer", "science"], "abbr": ["bscs"] },
  "economics": { "name": ["economics"], "abbr": [] },
  "electrical engineering": { "name": ["electrical", "engineering"], "abbr": ["bsee"] },
  "education": { "name": ["elementary", "education"], "abbr": ["bsed"] },
  "hotel and restaurant management": { "name": ["hotel", "and", "restaurant", "management"], "abbr": ["bshrm", "hrm"] },
  "industrial engineering": { "name": ["industrial", "engineering"], "abbr": ["bsie"] },
  "interior design": { "name": ["interior", "design"], "abbr": ["bsid"] },
  "mechanical engineering": { "name": ["mechanical", "engineering"], "abbr": ["bsme"] },
  "mathematics": { "name": ["mathematics"], "abbr": ["bsm"] },
  "philippine studies": { "name": ["philippine", "studies"], "abbr": ["bsps"] },
  "philosophy": { "name": ["philosophy"], "abbr": ["bsphilo"] },
  "physical education": { "name": ["physical", "education"], "abbr": ["bspe"] },
  "physics": { "name": ["physics"], "abbr": ["bsp", "physics"] },
  "political science": { "name": ["political", "science"], "abbr": ["polsci"] },
  "psychology": { "name": ["psychology"], "abbr": [] },
  "public administration": { "name": ["public", "administration"], "abbr": ["bspa"] },
  "social work": { "name": ["social", "work"], "abbr": ["bssw"] },
  "sociology": { "name": ["sociology"], "abbr": [] },
  "sport science": { "name": ["sport", "science"], "abbr": [] },
  "statistics": { "name": ["statistics"], "abbr": [] },
  "tourism management": { "name": ["tourism"], "abbr": ["bstm"] }
}
