EXPERIENCE_ROLES = {
  "graphic designer": { "name": ["graphic", "designer"] },
  "public relations": { "name": ["public", "relations"] },
  "event planner": { "name": ["event", "planner"] },
  "illustrator": { "name": ["illustrator"] },
  "accountant": { "name": ["accountant"] },
  "auditor": { "name": ["auditor"] },
  "financial manager": { "name": ["financial", "manager"] },
  "bookkeeper": { "name": ["bookkeeper"] },
  "financial advisor": { "name": ["financial", "advisor"] },
  "customer service representative": { "name": ["customer", "service", "representative"] },
  "tutor": { "name": ["tutor"] },
  "hotel and restaurant staff": { "name": ["hotel", "and", "restaurant", "staff"] },
  "chef": { "name": ["chef"] },
  "web developer": { "name": ["web", "developer"] },
  "database administrator": { "name": ["database", "administrator"] },
  "system analyst": { "name": ["system", "analyst"] },
  "application developer": { "name": ["application", "developer"] },
  "software engineer": { "name": ["software", "engineer"] },
  "medical assistant": { "name": ["medical", "assistant"] },
  "medical doctor": { "name": ["medical", "doctor"] },
  "registered nurse": { "name": ["registered", "nurse"] },
  "pharmacist": { "name": ["pharmacist"] },
  "medical laboratory technologist": { "name": ["medical", "laboratory", "technologist"] },
  "sped teacher": { "name": ["sped", "teacher"] },
  "researcher": { "name": ["researcher"] },
  "college professor": { "name": ["college", "professor"] },
  "recruiter": { "name": ["recruiter"] },
  "hr manager": { "name": ["hr", "manager"] },
  "offinance manager": { "name": ["offinance", "manager"] },
  "project coordinator": { "name": ["project", "coordinator"] },
  "clerk": { "name": ["clerk"] },
}
