EXPERIENCE_ROLES = {
  "interactive design specialist": {'name': ['interactive', 'design', 'specialist']},
  "multimedia designer": {'name': ['multimedia', 'designer']},
  "art director": {'name': ['art', 'director']},
  "visual art specialist": {'name': ['visual', 'art', 'specialist']},
  "graphic designer": {'name': ['graphic', 'designer']},
  "marketing coordinator": {'name': ['marketing', 'coordinator']},
  "public relations": {'name': ['public', 'relations']},
  "media content producer": {'name': ['media', 'content', 'producer']},
  "pr analyst": {'name': ['pr', 'analyst']},
  "production coordinator": {'name': ['production', 'coordinator']},
  "exhibit coordinator": {'name': ['exhibit', 'coordinator']},
  "coordinator": {'name': ['coordinator']},
  "event planner": {'name': ['event', 'planner']},
  "campaign planner": {'name': ['campaign', 'planner']},
  "communications coordinator": {'name': ['communications', 'coordinator']},
  "exhibition manager": {'name': ['exhibition', 'manager']},
  "digital artist": {'name': ['digital', 'artist']},
  "interactive designer": {'name': ['interactive', 'designer']},
  "multimedia producer": {'name': ['multimedia', 'producer']},
  "artistic director": {'name': ['artistic', 'director']},
  "illustrator": {'name': ['illustrator']},
  "financial manager": {'name': ['financial', 'manager']},
  "auditor": {'name': ['auditor']},
  "senior accountant": {'name': ['senior', 'accountant']},
  "junior accountant": {'name': ['junior', 'accountant']},
  "tax accountant": {'name': ['tax', 'accountant']},
  "junior bookkeeper": {'name': ['junior', 'bookkeeper']},
  "senior bookkeeper": {'name': ['senior', 'bookkeeper']},
  "junior auditor": {'name': ['junior', 'auditor']},
  "senior auditor": {'name': ['senior', 'auditor']},
  "taxation manager": {'name': ['taxation', 'manager']},
  "budgeting manager": {'name': ['budgeting', 'manager']},
  "financial analyst": {'name': ['financial', 'analyst']},
  "bookkeeper": {'name': ['bookkeeper']},
  "data analyst": {'name': ['data', 'analyst']},
  "financial controller": {'name': ['financial', 'controller']},
  "investment advisor": {'name': ['investment', 'advisor']},
  "financial system auditor": {'name': ['financial', 'system', 'auditor']},
  "forensic auditor": {'name': ['forensic', 'auditor']},
  "financial advisor": {'name': ['financial', 'advisor']},
  "support agent": {'name': ['support', 'agent']},
  "technical support": {'name': ['technical', 'support']},
  "client support": {'name': ['client', 'support']},
  "customer relations agent": {'name': ['customer', 'relations', 'agent']},
  "customer service representative": {'name': ['customer', 'service', 'representative']},
  "preschool tutor": {'name': ['preschool', 'tutor']},
  "tutor": {'name': ['tutor']},
  "preschool educator": {'name': ['preschool', 'educator']},
  "early learning specialist": {'name': ['early', 'learning', 'specialist']},
  "kindergarten tutor": {'name': ['kindergarten', 'tutor']},
  "language development specialist": {'name': ['language', 'development', 'specialist']},
  "early childhood specialist": {'name': ['early', 'childhood', 'specialist']},
  "esl tutor": {'name': ['esl', 'tutor']},
  "language tutor": {'name': ['language', 'tutor']},
  "science tutor": {'name': ['science', 'tutor']},
  "hotel concierge": {'name': ['hotel', 'concierge']},
  "operations manager": {'name': ['operations', 'manager']},
  "restaurant chef": {'name': ['restaurant', 'chef']},
  "receptionist": {'name': ['receptionist']},
  "housekeeper": {'name': ['housekeeper']},
  "executive chef": {'name': ['executive', 'chef']},
  "culinary director": {'name': ['culinary', 'director']},
  "pastry chef": {'name': ['pastry', 'chef']},
  "lead cook": {'name': ['lead', 'cook']},
  "sous chef": {'name': ['sous', 'chef']},
  "catering coordinator": {'name': ['catering', 'coordinator']},
  "concierge": {'name': ['concierge']},
  "marketing manager": {'name': ['marketing', 'manager']},
  "web developer": {'name': ['web', 'developer']},
  "software engineer": {'name': ['software', 'engineer']},
  "ui/ux web designer": {'name': ['ui/ux', 'web', 'designer']},
  "full stack web developer": {'name': ['full', 'stack', 'web', 'developer']},
  "web architect": {'name': ['web', 'architect']},
  "web security consultant": {'name': ['web', 'security', 'consultant']},
  "developer": {'name': ['developer']},
  "system analyst": {'name': ['system', 'analyst']},
  "database engineer": {'name': ['database', 'engineer']},
  "data engineer": {'name': ['data', 'engineer']},
  "database administrator": {'name': ['database', 'administrator']},
  "it analyst": {'name': ['it', 'analyst']},
  "database analyst": {'name': ['database', 'analyst']},
  "application analyst": {'name': ['application', 'analyst']},
  "it intern": {'name': ['it', 'intern']},
  "cybersecurity analyst": {'name': ['cybersecurity', 'analyst']},
  "support analyst": {'name': ['support', 'analyst']},
  "quality assurance analyst": {'name': ['quality', 'assurance', 'analyst']},
  "machine learning engineer": {'name': ['machine', 'learning', 'engineer']},
  "analyst": {'name': ['analyst']},
  "data scientist": {'name': ['data', 'scientist']},
  "software analyst": {'name': ['software', 'analyst']},
  "systems analyst": {'name': ['systems', 'analyst']},
  "app analyst": {'name': ['app', 'analyst']},
  "business analyst": {'name': ['business', 'analyst']},
  "operations analyst": {'name': ['operations', 'analyst']},
  "engineer": {'name': ['engineer']},
  "security analyst": {'name': ['security', 'analyst']},
  "security engineer": {'name': ['security', 'engineer']},
  "project analyst": {'name': ['project', 'analyst']},
  "manager": {'name': ['manager']},
  "compliance manager": {'name': ['compliance', 'manager']},
  "it consultant": {'name': ['it', 'consultant']},
  "systems engineer": {'name': ['systems', 'engineer']},
  "app developer": {'name': ['app', 'developer']},
  "mobile application engineer": {'name': ['mobile', 'application', 'engineer']},
  "mobile app specialist": {'name': ['mobile', 'app', 'specialist']},
  "mobile app engineer": {'name': ['mobile', 'app', 'engineer']},
  "mobile app ux/ui specialist": {'name': ['mobile', 'app', 'ux/ui', 'specialist']},
  "mobile app ai specialist": {'name': ['mobile', 'app', 'ai', 'specialist']},
  "game developer": {'name': ['game', 'developer']},
  "application developer": {'name': ['application', 'developer']},
  "full stack developer": {'name': ['full', 'stack', 'developer']},
  "project manager": {'name': ['project', 'manager']},
  "healthcare consultant": {'name': ['healthcare', 'consultant']},
  "medical assistant": {'name': ['medical', 'assistant']},
  "healthcare administrative assistant": {'name': ['healthcare', 'administrative', 'assistant']},
  "healthcare compliance officer": {'name': ['healthcare', 'compliance', 'officer']},
  "medical receptionist": {'name': ['medical', 'receptionist']},
  "physician": {'name': ['physician']},
  "occupational therapist": {'name': ['occupational', 'therapist']},
  "chief medical officer": {'name': ['chief', 'medical', 'officer']},
  "medical resident": {'name': ['medical', 'resident']},
  "er physician": {'name': ['er', 'physician']},
  "family medicine practitioner": {'name': ['family', 'medicine', 'practitioner']},
  "pediatric nurse": {'name': ['pediatric', 'nurse']},
  "operating room nurse": {'name': ['operating', 'room', 'nurse']},
  "medical surgical nurse": {'name': ['medical', 'surgical', 'nurse']},
  "icu nurse": {'name': ['icu', 'nurse']},
  "intensive care unit nurse": {'name': ['intensive', 'care', 'unit', 'nurse']},
  "clinical pharmacist": {'name': ['clinical', 'pharmacist']},
  "pharmacy technician": {'name': ['pharmacy', 'technician']},
  "compounding pharmacist": {'name': ['compounding', 'pharmacist']},
  "pharmacist": {'name': ['pharmacist']},
  "pharmaceutical researcher": {'name': ['pharmaceutical', 'researcher']},
  "pharmacy compliance officer": {'name': ['pharmacy', 'compliance', 'officer']},
  "microbiologist": {'name': ['microbiologist']},
  "lab scientist": {'name': ['lab', 'scientist']},
  "medical technologist": {'name': ['medical', 'technologist']},
  "lab assistant": {'name': ['lab', 'assistant']},
  "research lab technician": {'name': ['research', 'lab', 'technician']},
  "teacher's assistant": {'name': ["teacher's", 'assistant']},
  "teacher": {'name': ['teacher']},
  "sped teacher": {'name': ['sped', 'teacher']},
  "special education teacher": {'name': ['special', 'education', 'teacher']},
  "physical education teacher": {'name': ['physical', 'education', 'teacher']},
  "ai researcher": {'name': ['ai', 'researcher']},
  "assistant researcher": {'name': ['assistant', 'researcher']},
  "researcher": {'name': ['researcher']},
  "ux researcher": {'name': ['ux', 'researcher']},
  "data researcher": {'name': ['data', 'researcher']},
  "college professor": {'name': ['college', 'professor']},
  "business management professor": {'name': ['business', 'management', 'professor']},
  "psychology professor": {'name': ['psychology', 'professor']},
  "associate professor": {'name': ['associate', 'professor']},
  "professor": {'name': ['professor']},
  "recruiter": {'name': ['recruiter']},
  "admin recruiter": {'name': ['admin', 'recruiter']},
  "hr officer recruiter": {'name': ['hr', 'officer', 'recruiter']},
  "management recruiter": {'name': ['management', 'recruiter']},
  "junior recruiter": {'name': ['junior', 'recruiter']},
  "talent acquisition specialist": {'name': ['talent', 'acquisition', 'specialist']},
  "hr manager": {'name': ['hr', 'manager']},
  "office administrator": {'name': ['office', 'administrator']},
  "facilities coordinator": {'name': ['facilities', 'coordinator']},
  "administrative officer": {'name': ['administrative', 'officer']},
  "office manager": {'name': ['office', 'manager']},
  "event manager": {'name': ['event', 'manager']},
  "hr operations manager": {'name': ['hr', 'operations', 'manager']},
  "project coordinator": {'name': ['project', 'coordinator']},
  "administrative coordinator": {'name': ['administrative', 'coordinator']},
  "office operations coordinator": {'name': ['office', 'operations', 'coordinator']},
  "advertising coordinator": {'name': ['advertising', 'coordinator']},
  "clerk": {'name': ['clerk']},
  "administrative assistant": {'name': ['administrative', 'assistant']},
  "library assistant": {'name': ['library', 'assistant']},
}