EXPERIENCE_ROLES = {
  "graphic designer": {'name': ['graphic', 'designer']},
  "public relations": {'name': ['public', 'relations']},
  "event planner": {'name': ['event', 'planner']},
  "illustrator": {'name': ['illustrator']},
  "auditor": {'name': ['auditor']},
  "financial manager": {'name': ['financial', 'manager']},
  "bookkeeper": {'name': ['bookkeeper']},
  "financial advisor": {'name': ['financial', 'advisor']},
  "customer service representative": {'name': ['customer', 'service', 'representative']},
  "tutor": {'name': ['tutor']},
  "hotel and restaurant staff": {'name': ['hotel', 'and', 'restaurant', 'staff']},
  "chef": {'name': ['chef']},
  "web developer": {'name': ['web', 'developer']},
  "database administrator": {'name': ['database', 'administrator']},
  "system analyst": {'name': ['system', 'analyst']},
  "application developer": {'name': ['application', 'developer']},
  "developer": {'name': ['developer']},
  "software engineer": {'name': ['software', 'engineer']},
  "civil engineer": {'name': ['civil', 'engineer']},
  "mechanical engineer": {'name': ['mechanical', 'engineer']},
  "electrical engineer": {'name': ['electrical', 'engineer']},
  "medical assistant": {'name': ['medical', 'assistant']},
  "medical doctor": {'name': ['medical', 'doctor']},
  "doctor": {'name': ['doctor']},
  "nurse": {'name': ['nurse']},
  "registered nurse": {'name': ['registered', 'nurse']},
  "pharmacist": {'name': ['pharmacist']},
  "medical laboratory technologist": {'name': ['medical', 'laboratory', 'technologist']},
  "college professor": {'name': ['college', 'professor']},
  "recruiter": {'name': ['recruiter']},
  "hr manager": {'name': ['hr', 'manager']},
  "office manager": {'name': ['office', 'manager']},
  "coordinator": {'name': ['coordinator']},
  "project coordinator": {'name': ['project', 'coordinator']},
  "event coordinator": {'name': ['event', 'coordinator']},
  "event manager": {'name': ['event', 'manager']},
  "community event organizer": {'name': ['community', 'event', 'organizer']},
  "operations manager": {'name': ['operations', 'manager']},
  "logistics strategist": {'name': ['logistics', 'strategist']},
  "entertainment coordinator": {'name': ['entertainment', 'coordinator']},
  "event layout designer": {'name': ['event', 'layout', 'designer']},
  "event marketing strategist": {'name': ['event', 'marketing', 'strategist']},
  "venue contract negotiator": {'name': ['venue', 'contract', 'negotiator']},
  "event supervisor": {'name': ['event', 'supervisor']},
  "event designer": {'name': ['event', 'designer']},
  "marketing specialist": {'name': ['marketing', 'specialist']},
  "visual content creator": {'name': ['visual', 'content', 'creator']},
  "visual strategist": {'name': ['visual', 'strategist']},
  "brand designer": {'name': ['brand', 'designer']},
  "marketing designer": {'name': ['marketing', 'designer']},
  "ui/ux designer": {'name': ['ui/ux', 'designer']},
  "multimedia graphic producer": {'name': ['multimedia', 'graphic', 'producer']},
  "branding specialist": {'name': ['branding', 'specialist']},
  "marketing art producer": {'name': ['marketing', 'art', 'producer']},
  "digital art designer": {'name': ['digital', 'art', 'designer']},
  "icon and logo designer": {'name': ['icon', 'and', 'logo', 'designer']},
  "brand visual designer": {'name': ['brand', 'visual', 'designer']},
  "digital illustration producer": {'name': ['digital', 'illustration', 'producer']},
  "ui design innovator": {'name': ['ui', 'design', 'innovator']},
  "global campaign visual creator": {'name': ['global', 'campaign', 'visual', 'creator']},
  "typography designer": {'name': ['typography', 'designer']},
  "website layout revamper": {'name': ['website', 'layout', 'revamper']},
  "3d modeling animator": {'name': ['3d', 'modeling', 'animator']},
  "custom visual designer": {'name': ['custom', 'visual', 'designer']},
  "visual rebranding strategist": {'name': ['visual', 'rebranding', 'strategist']},
  "packaging design expert": {'name': ['packaging', 'design', 'expert']},
  "social media graphics creator": {'name': ['social', 'media', 'graphics', 'creator']},
  "interactive infographics designer": {'name': ['interactive', 'infographics', 'designer']},
  "ui/ux improvement specialist": {'name': ['ui/ux', 'improvement', 'specialist']},
  "motion graphics producer": {'name': ['motion', 'graphics', 'producer']},
  "visual storytelling strategist": {'name': ['visual', 'storytelling', 'strategist']},
  "mobile ux designer": {'name': ['mobile', 'ux', 'designer']},
  "market research-driven designer": {'name': ['market', 'research-driven', 'designer']},
  "visual-content synchronization collaborator": {'name': ['visual-content', 'synchronization', 'collaborator']},
  "accessibility design specialist": {'name': ['accessibility', 'design', 'specialist']},
  "design process streamliner": {'name': ['design', 'process', 'streamliner']},
  "visual concept translator": {'name': ['visual', 'concept', 'translator']},
  "design thinking prototyper": {'name': ['design', 'thinking', 'prototyper']},
  "user-centered experience designer": {'name': ['user-centered', 'experience', 'designer']},
  "responsive design specialist": {'name': ['responsive', 'design', 'specialist']},
  "usability refinement specialist": {'name': ['usability', 'refinement', 'specialist']},
  "email marketing visual creator": {'name': ['email', 'marketing', 'visual', 'creator']},
  "iconography enhancer": {'name': ['iconography', 'enhancer']},
  "innovative design concept pioneer": {'name': ['innovative', 'design', 'concept', 'pioneer']},
  "human-centric design problem solver": {'name': ['human-centric', 'design', 'problem', 'solver']},
  "pitch deck visual creator": {'name': ['pitch', 'deck', 'visual', 'creator']},
  "design-thinking infuser": {'name': ['design-thinking', 'infuser']},
  "system developer": {'name': ['system', 'developer']},
  "motion graphics integrator": {'name': ['motion', 'graphics', 'integrator']},
  "a/b testing designer": {'name': ['a/b', 'testing', 'designer']},
  "gamification interface implementer": {'name': ['gamification', 'interface', 'implementer']},
  "website navigation redesigner": {'name': ['website', 'navigation', 'redesigner']},
  "eco-friendly print material optimizer": {'name': ['eco-friendly', 'print', 'material', 'optimizer']},
  "social cause visual campaign creator": {'name': ['social', 'cause', 'visual', 'campaign', 'creator']},
  "interactive prototype creator": {'name': ['interactive', 'prototype', 'creator']},
  "custom illustration brand enhancer": {'name': ['custom', 'illustration', 'brand', 'enhancer']},
  "color psychology visual designer": {'name': ['color', 'psychology', 'visual', 'designer']},
  "accessibility-compliant website layout revamper": {'name': ['accessibility-compliant', 'website', 'layout', 'revamper']},
  "innovative typography designer": {'name': ['innovative', 'typography', 'designer']},
  "animated infographics creator": {'name': ['animated', 'infographics', 'creator']},
  "user interview collaborator": {'name': ['user', 'interview', 'collaborator']},
  "photo manipulation specialist": {'name': ['photo', 'manipulation', 'specialist']},
  "brand narrative visual designer": {'name': ['brand', 'narrative', 'visual', 'designer']},
  "social media engagement contributor": {'name': ['social', 'media', 'engagement', 'contributor']},
  "startup pitch deck creator": {'name': ['startup', 'pitch', 'deck', 'creator']},
  "data visualization designer": {'name': ['data', 'visualization', 'designer']},
  "interactive content producer": {'name': ['interactive', 'content', 'producer']},
  "product launch brand visualizer": {'name': ['product', 'launch', 'brand', 'visualizer']},
  "visual identity system executor": {'name': ['visual', 'identity', 'system', 'executor']},
  "grid layout designer": {'name': ['grid', 'layout', 'designer']},
  "editorial illustration enhancer": {'name': ['editorial', 'illustration', 'enhancer']},
  "business goal translator": {'name': ['business', 'goal', 'translator']},
  "stand-out packaging designer": {'name': ['stand-out', 'packaging', 'designer']},
  "user persona and journey mapper": {'name': ['user', 'persona', 'and', 'journey', 'mapper']},
  "responsive web designer": {'name': ['responsive', 'web', 'designer']},
  "usability tester": {'name': ['usability', 'tester']},
  "custom graphics and illustrations designer": {'name': ['custom', 'graphics', 'and', 'illustrations', 'designer']},
  "design thinking ui/ux problem solver": {'name': ['design', 'thinking', 'ui/ux', 'problem', 'solver']},
  "cross-functional design integrator": {'name': ['cross-functional', 'design', 'integrator']},
  "packaging designer": {'name': ['packaging', 'designer']},
  "visual storyteller": {'name': ['visual', 'storyteller']},
  "visual branding designer": {'name': ['visual', 'branding', 'designer']},
  "visual brand strategist": {'name': ['visual', 'brand', 'strategist']},
  "marketing design specialist": {'name': ['marketing', 'design', 'specialist']},
  "digital marketing visual designer": {'name': ['digital', 'marketing', 'visual', 'designer']},
  "multimedia visual designer": {'name': ['multimedia', 'visual', 'designer']},
  "interactive visual designer": {'name': ['interactive', 'visual', 'designer']},
  "marketing visual designer": {'name': ['marketing', 'visual', 'designer']},
  "marketing visualizer": {'name': ['marketing', 'visualizer']},
  "visual media specialist": {'name': ['visual', 'media', 'specialist']},
  "brand strategist": {'name': ['brand', 'strategist']},
  "design director": {'name': ['design', 'director']},
  "multimedia artist": {'name': ['multimedia', 'artist']},
  "visual design specialist": {'name': ['visual', 'design', 'specialist']},
  "visual content producer": {'name': ['visual', 'content', 'producer']},
  "visual designer": {'name': ['visual', 'designer']},
  "graphic content creator": {'name': ['graphic', 'content', 'creator']},
  "visual content designer": {'name': ['visual', 'content', 'designer']},
  "brand identity designer": {'name': ['brand', 'identity', 'designer']},
  "concept artist": {'name': ['concept', 'artist']},
  "visual branding specialist": {'name': ['visual', 'branding', 'specialist']},
  "ui/ux visual designer": {'name': ['ui/ux', 'visual', 'designer']},
  "brand visualizer": {'name': ['brand', 'visualizer']},
  "digital artist": {'name': ['digital', 'artist']},
  "multimedia designer": {'name': ['multimedia', 'designer']},
  "social media visual designer": {'name': ['social', 'media', 'visual', 'designer']},
  "web visual designer": {'name': ['web', 'visual', 'designer']},
  "mobile app visual artist": {'name': ['mobile', 'app', 'visual', 'artist']},
  "user interface designer": {'name': ['user', 'interface', 'designer']},
  "packaging visual designer": {'name': ['packaging', 'visual', 'designer']},
  "motion graphics designer": {'name': ['motion', 'graphics', 'designer']},
  "marketing graphic designer": {'name': ['marketing', 'graphic', 'designer']},
  "junior graphic designer": {'name': ['junior', 'graphic', 'designer']},
  "media content creator": {'name': ['media', 'content', 'creator']},
  "social media pr specialist": {'name': ['social', 'media', 'pr', 'specialist']},
  "pr assistant": {'name': ['pr', 'assistant']},
  "digital pr specialist": {'name': ['digital', 'pr', 'specialist']},
  "press relations manager": {'name': ['press', 'relations', 'manager']},
  "pr analyst": {'name': ['pr', 'analyst']},
  "influencer relations specialist": {'name': ['influencer', 'relations', 'specialist']},
  "media outreach assistant": {'name': ['media', 'outreach', 'assistant']},
  "media relations specialist": {'name': ['media', 'relations', 'specialist']},
  "pr campaign assistant": {'name': ['pr', 'campaign', 'assistant']},
  "online pr specialist": {'name': ['online', 'pr', 'specialist']},
  "press release specialist": {'name': ['press', 'release', 'specialist']},
  "storytelling content creator": {'name': ['storytelling', 'content', 'creator']},
  "digital pr strategist": {'name': ['digital', 'pr', 'strategist']},
  "nonprofit communication strategist": {'name': ['nonprofit', 'communication', 'strategist']},
  "brand narrative strategist": {'name': ['brand', 'narrative', 'strategist']},
  "financial analyst": {'name': ['financial', 'analyst']},
  "financial controler": {'name': ['financial', 'controler']},
  "budget analyst": {'name': ['budget', 'analyst']},
  "tax consultant": {'name': ['tax', 'consultant']},
  "financial reporting analyst": {'name': ['financial', 'reporting', 'analyst']},
  "risk management specialist": {'name': ['risk', 'management', 'specialist']},
  "tax analyst": {'name': ['tax', 'analyst']},
  "financial planner": {'name': ['financial', 'planner']},
  "cost analyst": {'name': ['cost', 'analyst']},
  "tax accountant": {'name': ['tax', 'accountant']},
  "audit manager": {'name': ['audit', 'manager']},
  "cost accountant": {'name': ['cost', 'accountant']},
  "financial systems analyst": {'name': ['financial', 'systems', 'analyst']},
  "tax manager": {'name': ['tax', 'manager']},
  "financial controller": {'name': ['financial', 'controller']},
  "budget manager": {'name': ['budget', 'manager']},
  "corporate treasurer": {'name': ['corporate', 'treasurer']},
  "financial system analyst": {'name': ['financial', 'system', 'analyst']},
  "risk manager": {'name': ['risk', 'manager']},
  "systems manager": {'name': ['systems', 'manager']},
  "trading manager": {'name': ['trading', 'manager']},
  "finance manager": {'name': ['finance', 'manager']},
  "compliance manager": {'name': ['compliance', 'manager']},
  "financial risk manager": {'name': ['financial', 'risk', 'manager']},
  "accounts assistant": {'name': ['accounts', 'assistant']},
  "assistant bookkeeper": {'name': ['assistant', 'bookkeeper']},
  "bookkeeping specialist": {'name': ['bookkeeping', 'specialist']},
  "accounting assistant": {'name': ['accounting', 'assistant']},
  "bookkeeping analyst": {'name': ['bookkeeping', 'analyst']},
  "bookkeeping administrator": {'name': ['bookkeeping', 'administrator']},
  "accounts payable specialist": {'name': ['accounts', 'payable', 'specialist']},
  "consultant": {'name': ['consultant']},
  "accounts receivable specialist": {'name': ['accounts', 'receivable', 'specialist']},
  "accounting administrator": {'name': ['accounting', 'administrator']},
  "advisor": {'name': ['advisor']},
  "financial consultant": {'name': ['financial', 'consultant']},
  "management advisor": {'name': ['management', 'advisor']},
  "retirement planning specialist": {'name': ['retirement', 'planning', 'specialist']},
  "investment advisor": {'name': ['investment', 'advisor']},
  "estate planning advisor": {'name': ['estate', 'planning', 'advisor']},
  "insurance advisor": {'name': ['insurance', 'advisor']},
  "tax planning specialist": {'name': ['tax', 'planning', 'specialist']},
  "debt management advisor": {'name': ['debt', 'management', 'advisor']},
  "college planning specialist": {'name': ['college', 'planning', 'specialist']},
  "budgeting advisor": {'name': ['budgeting', 'advisor']},
  "financial strategist": {'name': ['financial', 'strategist']},
  "behavioral finance specialist": {'name': ['behavioral', 'finance', 'specialist']},
  "financial wellness coach": {'name': ['financial', 'wellness', 'coach']},
  "financial education specialist": {'name': ['financial', 'education', 'specialist']},
  "financial coaching specialist": {'name': ['financial', 'coaching', 'specialist']},
  "finance advisor": {'name': ['finance', 'advisor']},
  "financing advisor": {'name': ['financing', 'advisor']},
  "behavioral coaching specialist": {'name': ['behavioral', 'coaching', 'specialist']},
  "retirement health specialist": {'name': ['retirement', 'health', 'specialist']},
  "personal finance educator": {'name': ['personal', 'finance', 'educator']},
  "venture capital advisor": {'name': ['venture', 'capital', 'advisor']},
  "capital advisor": {'name': ['capital', 'advisor']},
  "real estate tax planning specialist": {'name': ['real', 'estate', 'tax', 'planning', 'specialist']},
  "accountant": {'name': ['accountant']},
  "compliance officer": {'name': ['compliance', 'officer']},
  "international tax specialist": {'name': ['international', 'tax', 'specialist']},
  "forensic auditor": {'name': ['forensic', 'auditor']},
  "financial modeling specialist": {'name': ['financial', 'modeling', 'specialist']},
  "tax advisor": {'name': ['tax', 'advisor']},
  "financial systems auditor": {'name': ['financial', 'systems', 'auditor']},
  "cost estimation specialist": {'name': ['cost', 'estimation', 'specialist']},
  "financial software implementation specialist": {'name': ['financial', 'software', 'implementation', 'specialist']},
  "financial compliance officer": {'name': ['financial', 'compliance', 'officer']},
  "financial auditor": {'name': ['financial', 'auditor']},
  "sustainability reporting specialist": {'name': ['sustainability', 'reporting', 'specialist']},
  "financial systems integration specialist": {'name': ['financial', 'systems', 'integration', 'specialist']},
  "business valuation specialist": {'name': ['business', 'valuation', 'specialist']},
  "taxation manager": {'name': ['taxation', 'manager']},
  "budgeting manager": {'name': ['budgeting', 'manager']},
  "banking manager": {'name': ['banking', 'manager']},
  "accounting specialist": {'name': ['accounting', 'specialist']},
  "accounting manager": {'name': ['accounting', 'manager']},
  "bookkeeping manager": {'name': ['bookkeeping', 'manager']},
  "finance analyst": {'name': ['finance', 'analyst']},
  "freelance accounting specialist": {'name': ['freelance', 'accounting', 'specialist']},
  "bookkeeping assistant": {'name': ['bookkeeping', 'assistant']},
  "accounting and payroll specialist": {'name': ['accounting', 'and', 'payroll', 'specialist']},
  "data analyst": {'name': ['data', 'analyst']},
  "accounting analyst": {'name': ['accounting', 'analyst']},
  "wealth management associate": {'name': ['wealth', 'management', 'associate']},
  "investment strategist": {'name': ['investment', 'strategist']},
  "retirement income planner": {'name': ['retirement', 'income', 'planner']},
  "financial literacy advocate": {'name': ['financial', 'literacy', 'advocate']},
  "business succession planner": {'name': ['business', 'succession', 'planner']},
  "financial planning specialist": {'name': ['financial', 'planning', 'specialist']},
  "retirement income strategist": {'name': ['retirement', 'income', 'strategist']},
  "financial wellness specialist": {'name': ['financial', 'wellness', 'specialist']},
  "wealth advisor": {'name': ['wealth', 'advisor']},
  "tax efficiency specialist": {'name': ['tax', 'efficiency', 'specialist']},
  "retirement lifestyle planner": {'name': ['retirement', 'lifestyle', 'planner']},
  "financial innovation specialist": {'name': ['financial', 'innovation', 'specialist']},
  "retirement income specialist": {'name': ['retirement', 'income', 'specialist']},
  "corporate retirement specialist": {'name': ['corporate', 'retirement', 'specialist']},
  "global investment strategist": {'name': ['global', 'investment', 'strategist']},
  "tax auditor": {'name': ['tax', 'auditor']},
  "it auditor": {'name': ['it', 'auditor']},
  "audit analyst": {'name': ['audit', 'analyst']},
  "analyst": {'name': ['analyst']},
  "audit director": {'name': ['audit', 'director']},
  "forensic accounting investigator": {'name': ['forensic', 'accounting', 'investigator']},
  "forensic investigator": {'name': ['forensic', 'investigator']},
  "cybersecurity incident responder": {'name': ['cybersecurity', 'incident', 'responder']},
  "incident responder": {'name': ['incident', 'responder']},
  "customer sales representative": {'name': ['customer', 'sales', 'representative']},
  "customer service": {'name': ['customer', 'service']},
  "support representative": {'name': ['support', 'representative']},
  "csr specialist": {'name': ['csr', 'specialist']},
  "client support": {'name': ['client', 'support']},
  "customer representative": {'name': ['customer', 'representative']},
  "service agent": {'name': ['service', 'agent']},
  "customer advocate": {'name': ['customer', 'advocate']},
  "support associate": {'name': ['support', 'associate']},
  "client relations": {'name': ['client', 'relations']},
  "customer service specialist": {'name': ['customer', 'service', 'specialist']},
  "support rep": {'name': ['support', 'rep']},
  "service specialist": {'name': ['service', 'specialist']},
  "technical support": {'name': ['technical', 'support']},
  "billing specialist": {'name': ['billing', 'specialist']},
  "technical helpdesk agent": {'name': ['technical', 'helpdesk', 'agent']},
  "social media support": {'name': ['social', 'media', 'support']},
  "support agent": {'name': ['support', 'agent']},
  "remote support specialist": {'name': ['remote', 'support', 'specialist']},
  "support specialist": {'name': ['support', 'specialist']},
  "product knowledge specialist": {'name': ['product', 'knowledge', 'specialist']},
  "customer retention specialist": {'name': ['customer', 'retention', 'specialist']},
  "technical customer support": {'name': ['technical', 'customer', 'support']},
  "customer support": {'name': ['customer', 'support']},
  "order processing specialist": {'name': ['order', 'processing', 'specialist']},
  "helpdesk specialist": {'name': ['helpdesk', 'specialist']},
  "inbound calls specialist": {'name': ['inbound', 'calls', 'specialist']},
  "technical trainer": {'name': ['technical', 'trainer']},
  "order fulfillment specialist": {'name': ['order', 'fulfillment', 'specialist']},
  "quality assurance analyst": {'name': ['quality', 'assurance', 'analyst']},
  "fraud prevention specialist": {'name': ['fraud', 'prevention', 'specialist']},
  "technical documentation specialist": {'name': ['technical', 'documentation', 'specialist']},
  "customer analytics specialist": {'name': ['customer', 'analytics', 'specialist']},
  "product feedback specialist": {'name': ['product', 'feedback', 'specialist']},
  "ai chatbot trainer": {'name': ['ai', 'chatbot', 'trainer']},
  "billing dispute specialist": {'name': ['billing', 'dispute', 'specialist']},
  "support analyst": {'name': ['support', 'analyst']},
  "customer onboarding specialist": {'name': ['customer', 'onboarding', 'specialist']},
  "customer engagement specialist": {'name': ['customer', 'engagement', 'specialist']},
  "technical documentation writer": {'name': ['technical', 'documentation', 'writer']},
  "order tracking specialist": {'name': ['order', 'tracking', 'specialist']},
  "customer data privacy specialist": {'name': ['customer', 'data', 'privacy', 'specialist']},
  "customer support specialist": {'name': ['customer', 'support', 'specialist']},
  "customer advocacy specialist": {'name': ['customer', 'advocacy', 'specialist']},
  "customer loyalty specialist": {'name': ['customer', 'loyalty', 'specialist']},
  "sales support": {'name': ['sales', 'support']},
  "customer wellness specialist": {'name': ['customer', 'wellness', 'specialist']},
  "customer journey specialist": {'name': ['customer', 'journey', 'specialist']},
  "preschool tutor": {'name': ['preschool', 'tutor']},
  "preschool educator": {'name': ['preschool', 'educator']},
  "educator": {'name': ['educator']},
  "early learning specialist": {'name': ['early', 'learning', 'specialist']},
  "kindergarten tutor": {'name': ['kindergarten', 'tutor']},
  "early childhood specialist": {'name': ['early', 'childhood', 'specialist']},
  "esl tutor": {'name': ['esl', 'tutor']},
  "language development specialist": {'name': ['language', 'development', 'specialist']},
  "language tutor": {'name': ['language', 'tutor']},
  "science tutor": {'name': ['science', 'tutor']},
  "receptionist": {'name': ['receptionist']},
  "hotel front office rep": {'name': ['hotel', 'front', 'office', 'rep']},
  "guest services associate": {'name': ['guest', 'services', 'associate']},
  "front office specialist": {'name': ['front', 'office', 'specialist']},
  "front desk agent": {'name': ['front', 'desk', 'agent']},
  "guest relations officer": {'name': ['guest', 'relations', 'officer']},
  "hotel receptionist": {'name': ['hotel', 'receptionist']},
  "guest service representative": {'name': ['guest', 'service', 'representative']},
  "hotel concierge": {'name': ['hotel', 'concierge']},
  "reservation specialist": {'name': ['reservation', 'specialist']},
  "front desk specialist": {'name': ['front', 'desk', 'specialist']},
  "front office representative": {'name': ['front', 'office', 'representative']},
  "events coordinator": {'name': ['events', 'coordinator']},
  "guest relations specialist": {'name': ['guest', 'relations', 'specialist']},
  "concierge": {'name': ['concierge']},
  "reservation agent": {'name': ['reservation', 'agent']},
  "sales coordinator": {'name': ['sales', 'coordinator']},
  "catering coordinator": {'name': ['catering', 'coordinator']},
  "event sales manager": {'name': ['event', 'sales', 'manager']},
  "sales manager": {'name': ['sales', 'manager']},
  "spa therapist": {'name': ['spa', 'therapist']},
  "it support specialist": {'name': ['it', 'support', 'specialist']},
  "fitness instructor": {'name': ['fitness', 'instructor']},
  "executive chef": {'name': ['executive', 'chef']},
  "hr specialist": {'name': ['hr', 'specialist']},
  "project manager": {'name': ['project', 'manager']},
  "public relations specialist": {'name': ['public', 'relations', 'specialist']},
  "head bartender": {'name': ['head', 'bartender']},
  "hotel sales manager": {'name': ['hotel', 'sales', 'manager']},
  "pastry chef": {'name': ['pastry', 'chef']},
  "restaurant supervisor": {'name': ['restaurant', 'supervisor']},
  "barista": {'name': ['barista']},
  "executive housekeeper": {'name': ['executive', 'housekeeper']},
  "banquet chef": {'name': ['banquet', 'chef']},
  "restaurant bartender": {'name': ['restaurant', 'bartender']},
  "restaurant host": {'name': ['restaurant', 'host']},
  "room attendant": {'name': ['room', 'attendant']},
  "restaurant manager": {'name': ['restaurant', 'manager']},
  "bar supervisor": {'name': ['bar', 'supervisor']},
  "banquet server": {'name': ['banquet', 'server']},
  "kitchen steward": {'name': ['kitchen', 'steward']},
  "coffee barista": {'name': ['coffee', 'barista']},
  "sous chef": {'name': ['sous', 'chef']},
  "hotel sales executive": {'name': ['hotel', 'sales', 'executive']},
  "restaurant chef": {'name': ['restaurant', 'chef']},
  "restaurant server": {'name': ['restaurant', 'server']},
  "hotel front office assistant": {'name': ['hotel', 'front', 'office', 'assistant']},
  "restaurant expeditor": {'name': ['restaurant', 'expeditor']},
  "cook": {'name': ['buffet', 'line', 'cook']},
  "lead cook": {'name': ['lead', 'cook']},
  "head chef": {'name': ['head', 'chef']},
  "sushi chef": {'name': ['sushi', 'chef']},
  "italian chef": {'name': ['italian', 'chef']},
  "mexican chef": {'name': ['mexican', 'chef']},
  "grill chef": {'name': ['grill', 'chef']},
  "mediterranean chef": {'name': ['mediterranean', 'chef']},
  "seafood chef": {'name': ['seafood', 'chef']},
  "vegetable chef": {'name': ['vegetable', 'chef']},
  "vegetarian chef": {'name': ['vegetarian', 'chef']},
  "caribbean chef": {'name': ['caribbean', 'chef']},
  "steakhouse chef": {'name': ['steakhouse', 'chef']},
  "dessert chef": {'name': ['dessert', 'chef']},
  "culinary director": {'name': ['culinary', 'director']},
  "buffet culinary director": {'name': ['buffet', 'culinary', 'director']},
  "culinary specialist": {'name': ['culinary', 'specialist']},
  "culinary researcher": {'name': ['culinary', 'researcher']},
  "culinary operations manager": {'name': ['culinary', 'operations', 'manager']},
  "seafood specialist": {'name': ['seafood', 'specialist']},
  "catering director": {'name': ['catering', 'director']},
  "supervisor": {'name': ['supervisor']},
  "quality assurance specialist": {'name': ['quality', 'assurance', 'specialist']},
  "qa specialist": {'name': ['qa', 'specialist']},
  "development manager": {'name': ['development', 'manager']},
  "innovation manager": {'name': ['innovation', 'manager']},
  "catering manager": {'name': ['catering', 'manager']},
  "catering consultant": {'name': ['catering', 'consultant']},
  "catering supervisor": {'name': ['catering', 'supervisor']},
  "catering specialist": {'name': ['catering', 'specialist']},
  "frontend developer": {'name': ['frontend', 'developer']},
  "full stack developer": {'name': ['full', 'stack', 'developer']},
  "backend developer": {'name': ['backend', 'developer']},
  "app developer": {'name': ['app', 'developer']},
  "database developer": {'name': ['database', 'developer']},
  "frontend architect": {'name': ['frontend', 'architect']},
  "cybersecurity developer": {'name': ['cybersecurity', 'developer']},
  "cloud solutions architect": {'name': ['cloud', 'solutions', 'architect']},
  "machine learning developer": {'name': ['machine', 'learning', 'developer']},
  "web accessibility specialist": {'name': ['web', 'accessibility', 'specialist']},
  "game developer": {'name': ['game', 'developer']},
  "framework developer": {'name': ['framework', 'developer']},
  "web security consultant": {'name': ['web', 'security', 'consultant']},
  "database specialist": {'name': ['database', 'specialist']},
  "database engineer": {'name': ['database', 'engineer']},
  "engineer": {'name': ['engineer']},
  "database analyst": {'name': ['database', 'analyst']},
  "database manager": {'name': ['database', 'manager']},
  "database architect": {'name': ['database', 'architect']},
  "database security expert": {'name': ['database', 'security', 'expert']},
  "database management consultant": {'name': ['database', 'management', 'consultant']},
  "data security specialist": {'name': ['data', 'security', 'specialist']},
  "systems analyst": {'name': ['systems', 'analyst']},
  "cybersecurity analyst": {'name': ['cybersecurity', 'analyst']},
  "database systems architect": {'name': ['database', 'systems', 'architect']},
  "database security analyst": {'name': ['database', 'security', 'analyst']},
  "security analyst": {'name': ['security', 'analyst']},
  "it analyst": {'name': ['it', 'analyst']},
  "software developer": {'name': ['software', 'developer']},
  "systems engineer": {'name': ['systems', 'engineer']},
  "business systems analyst": {'name': ['business', 'systems', 'analyst']},
  "application analyst": {'name': ['application', 'analyst']},
  "it consultant": {'name': ['it', 'consultant']},
  "technical support analyst": {'name': ['technical', 'support', 'analyst']},
  "ux/ui designer": {'name': ['ux/ui', 'designer']},
  "machine learning engineer": {'name': ['machine', 'learning', 'engineer']},
  "data scientist": {'name': ['data', 'scientist']},
  "software analyst": {'name': ['software', 'analyst']},
  "business analyst": {'name': ['business', 'analyst']},
  "operations analyst": {'name': ['operations', 'analyst']},
  "cloud security architect": {'name': ['cloud', 'security', 'architect']},
  "project analyst": {'name': ['project', 'analyst']},
  "app analyst": {'name': ['app', 'analyst']},
  "business systems integrator": {'name': ['business', 'systems', 'integrator']},
  "it intern": {'name': ['it', 'intern']},
  "technical writer": {'name': ['technical', 'writer']},
  "trainee ux/ui designer": {'name': ['trainee', 'ux/ui', 'designer']},
  "programming intern": {'name': ['programming', 'intern']},
  "it trainee": {'name': ['it', 'trainee']},
  "systems integration intern": {'name': ['systems', 'integration', 'intern']},
  "mobile app specialist": {'name': ['mobile', 'app', 'specialist']},
  "mobile application specialist": {'name': ['mobile', 'application', 'specialist']},
  "application specialist": {'name': ['application', 'specialist']},
  "mobile app engineer": {'name': ['mobile', 'app', 'engineer']},
  "mobile application engineer": {'name': ['mobile', 'application', 'engineer']},
  "mobile app ux/ui specialist": {'name': ['mobile', 'app', 'ux/ui', 'specialist']},
  "ux/ui specialist": {'name': ['ux/ui', 'specialist']},
  "cybersecurity specialist": {'name': ['cybersecurity', 'specialist']},
  "mobile app ai specialist": {'name': ['mobile', 'app', 'ai', 'specialist']},
  "ai specialist": {'name': ['ai', 'specialist']},
  "artificial intelligence specialist": {'name': ['artificial', 'intelligence', 'specialist']},
  "security engineer": {'name': ['security', 'engineer']},
  "security developer": {'name': ['security', 'developer']},
  "ai developer": {'name': ['ai', 'developer']},
  "artificial intelligence developer": {'name': ['artificial', 'intelligence', 'developer']},
  "ux researcher": {'name': ['ux', 'researcher']},
  "ui/ux researcher": {'name': ['ui/ux', 'researcher']},
  "ux/ui researcher": {'name': ['ux/ui', 'researcher']},
  "scrum master": {'name': ['scrum', 'master']},
  "game designer": {'name': ['game', 'designer']},
  "ui developer": {'name': ['ui', 'developer']},
  "ai research scientist": {'name': ['ai', 'research', 'scientist']},
  "robotics engineer": {'name': ['robotics', 'engineer']},
  "software development engineer": {'name': ['software', 'development', 'engineer']},
  "software architect": {'name': ['software', 'architect']},
  "phlebotomist": {'name': ['phlebotomist']},
  "medical scribe": {'name': ['medical', 'scribe']},
  "medical billing specialist": {'name': ['medical', 'billing', 'specialist']},
  "medical assistant intern": {'name': ['medical', 'assistant', 'intern']},
  "certified nursing assistant (cna)": {'name': ['certified', 'nursing', 'assistant', '(cna)']},
  "healthcare administrative assistant": {'name': ['healthcare', 'administrative', 'assistant']},
  "medical interpreter": {'name': ['medical', 'interpreter']},
  "pharmacy technician": {'name': ['pharmacy', 'technician']},
  "health educator": {'name': ['health', 'educator']},
  "rehabilitation aide": {'name': ['rehabilitation', 'aide']},
  "radiologic technologist": {'name': ['radiologic', 'technologist']},
  "medical equipment technician": {'name': ['medical', 'equipment', 'technician']},
  "patient services representative": {'name': ['patient', 'services', 'representative']},
  "occupational therapy assistant": {'name': ['occupational', 'therapy', 'assistant']},
  "surgical technologist": {'name': ['surgical', 'technologist']},
  "medical receptionist": {'name': ['medical', 'receptionist']},
  "cardiac sonographer": {'name': ['cardiac', 'sonographer']},
  "community health worker": {'name': ['community', 'health', 'worker']},
  "neurodiagnostic technologist": {'name': ['neurodiagnostic', 'technologist']},
  "hospital administrator": {'name': ['hospital', 'administrator']},
  "chiropractic assistant": {'name': ['chiropractic', 'assistant']},
  "healthcare compliance officer": {'name': ['healthcare', 'compliance', 'officer']},
  "dental assistant": {'name': ['dental', 'assistant']},
  "healthcare consultant": {'name': ['healthcare', 'consultant']},
  "medical transcriptionist": {'name': ['medical', 'transcriptionist']},
  "genetic counselor": {'name': ['genetic', 'counselor']},
  "home health aide": {'name': ['home', 'health', 'aide']},
  "healthcare it specialist": {'name': ['healthcare', 'it', 'specialist']},
  "optometric technician": {'name': ['optometric', 'technician']},
  "manager": {'name': ['manager']},
  "medical equipment sales representative": {'name': ['medical', 'equipment', 'sales', 'representative']},
  "acupuncturist": {'name': ['acupuncturist']},
  "healthcare social worker": {'name': ['healthcare', 'social', 'worker']},
  "medical equipment repair technician": {'name': ['medical', 'equipment', 'repair', 'technician']},
  "occupational therapist": {'name': ['occupational', 'therapist']},
  "medical coding specialist": {'name': ['medical', 'coding', 'specialist']},
  "physical therapist": {'name': ['physical', 'therapist']},
  "healthcare marketing specialist": {'name': ['healthcare', 'marketing', 'specialist']},
  "dietitian": {'name': ['dietitian']},
  "health information technician": {'name': ['health', 'information', 'technician']},
  "medical office assistant": {'name': ['medical', 'office', 'assistant']},
  "medical laboratory assistant": {'name': ['medical', 'laboratory', 'assistant']},
  "healthcare receptionist": {'name': ['healthcare', 'receptionist']},
  "medical sales representative": {'name': ['medical', 'sales', 'representative']},
  "art therapist": {'name': ['art', 'therapist']},
  "medical claims processor": {'name': ['medical', 'claims', 'processor']},
  "cardiovascular technologist": {'name': ['cardiovascular', 'technologist']},
  "dental hygienist": {'name': ['dental', 'hygienist']},
  "respiratory therapist": {'name': ['respiratory', 'therapist']},
  "medical collections specialist": {'name': ['medical', 'collections', 'specialist']},
  "mental health counselor": {'name': ['mental', 'health', 'counselor']},
  "physical therapy assistant": {'name': ['physical', 'therapy', 'assistant']},
  "healthcare customer service representative": {'name': ['healthcare', 'customer', 'service', 'representative']},
  "medical imaging technologist": {'name': ['medical', 'imaging', 'technologist']},
  "surgeon": {'name': ['surgeon']},
  "orthopedic surgeon": {'name': ['orthopedic', 'surgeon']},
  "speech-language pathologist": {'name': ['speech-language', 'pathologist']},
  "medical ethics consultant": {'name': ['medical', 'ethics', 'consultant']},
  "podiatrist": {'name': ['podiatrist']},
  "anesthesiologist": {'name': ['anesthesiologist']},
  "nutritionist": {'name': ['nutritionist']},
  "technology analyst": {'name': ['technology', 'analyst']},
  "healthcare equipment procurement specialist": {'name': ['healthcare', 'equipment', 'procurement', 'specialist']},
  "medical resident": {'name': ['medical', 'resident']},
  "physician": {'name': ['physician']},
  "er physician": {'name': ['er', 'physician']},
  "general practitioner": {'name': ['general', 'practitioner']},
  "junior surgeon": {'name': ['junior', 'surgeon']},
  "chief medical officer": {'name': ['chief', 'medical', 'officer']},
  "obstetrician": {'name': ['obstetrician']},
  "cardiologist": {'name': ['cardiologist']},
  "junior pediatrician": {'name': ['junior', 'pediatrician']},
  "gynecologic oncologist": {'name': ['gynecologic', 'oncologist']},
  "urologist": {'name': ['urologist']},
  "junior emergency physician": {'name': ['junior', 'emergency', 'physician']},
  "psychiatrist": {'name': ['psychiatrist']},
  "pediatric surgeon": {'name': ['pediatric', 'surgeon']},
  "gastroenterologist": {'name': ['gastroenterologist']},
  "allergist": {'name': ['allergist']},
  "junior gynecologist": {'name': ['junior', 'gynecologist']},
  "family medicine practitioner": {'name': ['family', 'medicine', 'practitioner']},
  "dermatologist": {'name': ['dermatologist']},
  "plastic surgeon": {'name': ['plastic', 'surgeon']},
  "radiologist": {'name': ['radiologist']},
  "junior neurologist": {'name': ['junior', 'neurologist']},
  "orthodontist": {'name': ['orthodontist']},
  "ophthalmologist": {'name': ['ophthalmologist']},
  "chiropractor": {'name': ['chiropractor']},
  "junior ent specialist": {'name': ['junior', 'ent', 'specialist']},
  "rheumatologist": {'name': ['rheumatologist']},
  "interventional radiologist": {'name': ['interventional', 'radiologist']},
  "junior endocrinologist": {'name': ['junior', 'endocrinologist']},
  "pulmonologist": {'name': ['pulmonologist']},
  "neurosurgeon": {'name': ['neurosurgeon']},
  "chief of surgery": {'name': ['chief', 'of', 'surgery']},
  "medical researcher": {'name': ['medical', 'researcher']},
  "intensive care unit nurse": {'name': ['intensive', 'care', 'unit', 'nurse']},
  "operating room nurse": {'name': ['operating', 'room', 'nurse']},
  "pediatric nurse": {'name': ['pediatric', 'nurse']},
  "family medicine physician": {'name': ['family', 'medicine', 'physician']},
  "healthcare administrator": {'name': ['healthcare', 'administrator']},
  "medical writer": {'name': ['medical', 'writer']},
  "psychologist": {'name': ['psychologist']},
  "clinical psychologist": {'name': ['clinical', 'psychologist']},
  "emergency medical technician (emt)": {'name': ['emergency', 'medical', 'technician', '(emt)']},
  "clinical pharmacist": {'name': ['clinical', 'pharmacist']},
  "medical social worker": {'name': ['medical', 'social', 'worker']},
  "medical librarian": {'name': ['medical', 'librarian']},
  "patient advocate": {'name': ['patient', 'advocate']},
  "sleep technologist": {'name': ['sleep', 'technologist']},
  "medical coder": {'name': ['medical', 'coder']},
  "massage therapist": {'name': ['massage', 'therapist']},
  "optometrist": {'name': ['optometrist']},
  "medical biller": {'name': ['medical', 'biller']},
  "icu nurse": {'name': ['icu', 'nurse']},
  "pharmacy intern": {'name': ['pharmacy', 'intern']},
  "pharmacy director": {'name': ['pharmacy', 'director']},
  "pharmacy assistant": {'name': ['pharmacy', 'assistant']},
  "compounding pharmacist": {'name': ['compounding', 'pharmacist']},
  "pharmacy technician trainee": {'name': ['pharmacy', 'technician', 'trainee']},
  "pharmacy consultant": {'name': ['pharmacy', 'consultant']},
  "pharmaceutical researcher": {'name': ['pharmaceutical', 'researcher']},
  "pharmacy compliance officer": {'name': ['pharmacy', 'compliance', 'officer']},
  "antimicrobial stewardship pharmacist": {'name': ['antimicrobial', 'stewardship', 'pharmacist']},
  "lab technician": {'name': ['lab', 'technician']},
  "lab technologist": {'name': ['lab', 'technologist']},
  "medical technologist": {'name': ['medical', 'technologist']},
  "clinical lab scientist": {'name': ['clinical', 'lab', 'scientist']},
  "lab scientist": {'name': ['lab', 'scientist']},
  "scientist": {'name': ['scientist']},
  "lab supervisor": {'name': ['lab', 'supervisor']},
  "lab assistant": {'name': ['lab', 'assistant']},
  "research lab technician": {'name': ['research', 'lab', 'technician']},
  "lab director": {'name': ['lab', 'director']},
  "cytotechnologist": {'name': ['cytotechnologist']},
  "histotechnologist": {'name': ['histotechnologist']},
  "transfusion medicine specialist": {'name': ['transfusion', 'medicine', 'specialist']},
  "genetic lab technologist": {'name': ['genetic', 'lab', 'technologist']},
  "infectious disease specialist": {'name': ['infectious', 'disease', 'specialist']},
  "lab compliance officer": {'name': ['lab', 'compliance', 'officer']},
  "microbiologist": {'name': ['microbiologist']},
  "lab operations manager": {'name': ['lab', 'operations', 'manager']},
  "lab billing specialist": {'name': ['lab', 'billing', 'specialist']},
  "lab facilities manager": {'name': ['lab', 'facilities', 'manager']},
  "facilities manager": {'name': ['facilities', 'manager']},
  "lab instrumentation specialist": {'name': ['lab', 'instrumentation', 'specialist']},
  "lab automation specialist": {'name': ['lab', 'automation', 'specialist']},
  "cardiovascular lab technologist": {'name': ['cardiovascular', 'lab', 'technologist']},
  "lab equipment sales representative": {'name': ['lab', 'equipment', 'sales', 'representative']},
  "quality manager": {'name': ['quality', 'manager']},
  "lab supply chain specialist": {'name': ['lab', 'supply', 'chain', 'specialist']},
  "lab safety officer": {'name': ['lab', 'safety', 'officer']},
  "lab public relations specialist": {'name': ['lab', 'public', 'relations', 'specialist']},
  "lab artificial intelligence specialist": {'name': ['lab', 'artificial', 'intelligence', 'specialist']},
  "teacher's assistant": {'name': ["teacher's", 'assistant']},
  "teacher": {'name': ['teacher']},
  "sped teacher": {'name': ['certified', 'sped', 'teacher']},
  "pe teacher": {'name': ['pe', 'teacher']},
  "special education teacher": {'name': ['special', 'education', 'teacher']},
  "kindergarten teacher": {'name': ['kindergarten', 'teacher']},
  "english teacher": {'name': ['english', 'teacher']},
  "school psychologist": {'name': ['school', 'psychologist']},
  "school counselor": {'name': ['school', 'counselor']},
  "physical education teacher": {'name': ['physical', 'education', 'teacher']},
  "ai researcher": {'name': ['ai', 'researcher']},
  "assistant researcher": {'name': ['assistant', 'researcher']},
  "product owner": {'name': ['product', 'owner']},
  "academic tutor": {'name': ['academic', 'tutor']},
  "associate producer": {'name': ['associate', 'producer']},
  "proofreader": {'name': ['proofreader']},
  "contributor": {'name': ['contributor']},
  "web editor": {'name': ['web', 'editor']},
  "program coordinator": {'name': ['program', 'coordinator']},
  "masters in journalism": {'name': ['masters', 'in', 'journalism']},
  "ux designer": {'name': ['ux', 'designer']},
  "design researcher": {'name': ['design', 'researcher']},
  "field researcher": {'name': ['field', 'researcher']},
  "clinical researcher": {'name': ['clinical', 'researcher']},
  "researcher": {'name': ['researcher']},
  "wildlife biologist": {'name': ['wildlife', 'biologist']},
  "market researcher": {'name': ['market', 'researcher']},
  "linguistics researcher": {'name': ['linguistics', 'researcher']},
  "economic researcher": {'name': ['economic', 'researcher']},
  "renewable energy researcher": {'name': ['renewable', 'energy', 'researcher']},
  "astrophysics researcher": {'name': ['astrophysics', 'researcher']},
  "social science researcher": {'name': ['social', 'science', 'researcher']},
  "cognitive psychology researcher": {'name': ['cognitive', 'psychology', 'researcher']},
  "psychology researcher": {'name': ['psychology', 'researcher']},
  "clinical research scientist": {'name': ['clinical', 'research', 'scientist']},
  "behavioral psychology researcher": {'name': ['behavioral', 'psychology', 'researcher']},
  "cybersecurity researcher": {'name': ['cybersecurity', 'researcher']},
  "biomedical research scientist": {'name': ['biomedical', 'research', 'scientist']},
  "machine learning researcher": {'name': ['machine', 'learning', 'researcher']},
  "cognitive neuroscientist": {'name': ['cognitive', 'neuroscientist']},
  "artificial intelligence researcher": {'name': ['artificial', 'intelligence', 'researcher']},
  "content writer": {'name': ['content', 'writer']},
  "data researcher": {'name': ['data', 'researcher']},
  "environmental scientist": {'name': ['environmental', 'scientist']},
  "political science researcher": {'name': ['political', 'science', 'researcher']},
  "quantum physics researcher": {'name': ['quantum', 'physics', 'researcher']},
  "economics lecturer": {'name': ['economics', 'lecturer']},
  "literature professor": {'name': ['literature', 'professor']},
  "chemistry professor": {'name': ['chemistry', 'professor']},
  "finance instructor": {'name': ['finance', 'instructor']},
  "political science educator": {'name': ['political', 'science', 'educator']},
  "physics professor": {'name': ['physics', 'professor']},
  "marketing professor": {'name': ['marketing', 'professor']},
  "psychology lecturer": {'name': ['psychology', 'lecturer']},
  "history educator": {'name': ['history', 'educator']},
  "computer engineering professor": {'name': ['computer', 'engineering', 'professor']},
  "biology professor": {'name': ['biology', 'professor']},
  "statistics lecturer": {'name': ['statistics', 'lecturer']},
  "engineering professor": {'name': ['engineering', 'professor']},
  "philosophy professor": {'name': ['philosophy', 'professor']},
  "environmental science educator": {'name': ['environmental', 'science', 'educator']},
  "mathematics professor": {'name': ['mathematics', 'professor']},
  "math professor": {'name': ['math', 'professor']},
  "art history professor": {'name': ['art', 'history', 'professor']},
  "art professor": {'name': ['art', 'professor']},
  "history professor": {'name': ['history', 'professor']},
  "sociology lecturer": {'name': ['sociology', 'lecturer']},
  "electrical engineering professor": {'name': ['electrical', 'engineering', 'professor']},
  "foreign language professor": {'name': ['foreign', 'language', 'professor']},
  "language professor": {'name': ['language', 'professor']},
  "anthropology professor": {'name': ['anthropology', 'professor']},
  "music theory instructor": {'name': ['music', 'theory', 'instructor']},
  "business management professor": {'name': ['business', 'management', 'professor']},
  "assistant professor": {'name': ['assistant', 'professor']},
  "microbiology professor": {'name': ['microbiology', 'professor']},
  "marketing lecturer": {'name': ['marketing', 'lecturer']},
  "literature instructor": {'name': ['literature', 'instructor']},
  "physics educator": {'name': ['physics', 'educator']},
  "finance professor": {'name': ['finance', 'professor']},
  "political science professor": {'name': ['political', 'science', 'professor']},
  "computer science educator": {'name': ['computer', 'science', 'educator']},
  "environmental science professor": {'name': ['environmental', 'science', 'professor']},
  "psychology professor": {'name': ['psychology', 'professor']},
  "history lecturer": {'name': ['history', 'lecturer']},
  "civil engineering professor": {'name': ['civil', 'engineering', 'professor']},
  "genetics professor": {'name': ['genetics', 'professor']},
  "data science instructor": {'name': ['data', 'science', 'instructor']},
  "philosophy educator": {'name': ['philosophy', 'educator']},
  "renewable energy professor": {'name': ['renewable', 'energy', 'professor']},
  "art history educator": {'name': ['art', 'history', 'educator']},
  "sociology professor": {'name': ['sociology', 'professor']},
  "electrical engineering instructor": {'name': ['electrical', 'engineering', 'instructor']},
  "linguistics professor": {'name': ['linguistics', 'professor']},
  "cultural anthropology professor": {'name': ['cultural', 'anthropology', 'professor']},
  "music theory lecturer": {'name': ['music', 'theory', 'lecturer']},
  "business strategy professor": {'name': ['business', 'strategy', 'professor']},
  "retina surgeon": {'name': ['retina', 'surgeon']},
  "associate professor, director, chairman": {'name': ['associate', 'professor', 'director', 'chairman']},
  "hr & administrative officer": {'name': ['hr', '&', 'administrative', 'officer']},
  "lecturer": {'name': ['lecturer']},
  "associate professor": {'name': ['associate', 'professor']},
  "professor": {'name': ['professor']},
  "instructor": {'name': ['instructor']},
  "medical anthropology professor": {'name': ['medical', 'anthropology', 'professor']},
  "jazz music professor": {'name': ['jazz', 'music', 'professor']},
  "entrepreneurship professor": {'name': ['entrepreneurship', 'professor']},
  "economics professor": {'name': ['economics', 'professor']},
  "accounting professor": {'name': ['accounting', 'professor']},
  "human resources professor": {'name': ['human', 'resources', 'professor']},
  "information systems professor": {'name': ['information', 'systems', 'professor']},
  "english literature professor": {'name': ['english', 'literature', 'professor']},
  "nursing professor": {'name': ['nursing', 'professor']},
  "computer science professor": {'name': ['computer', 'science', 'professor']},
  "admin recruiter": {'name': ['admin', 'recruiter']},
  "hr officer recruiter": {'name': ['hr', 'officer', 'recruiter']},
  "technical corporate recruiter": {'name': ['technical', 'corporate', 'recruiter']},
  "corporate recruiter": {'name': ['corporate', 'recruiter']},
  "talent acquisition specialist": {'name': ['talent', 'acquisition', 'specialist']},
  "recruitment officer": {'name': ['recruitment', 'officer']},
  "recruiting specialist": {'name': ['recruiting', 'specialist']},
  "hr assistant": {'name': ['hr', 'assistant']},
  "recruitment specialist": {'name': ['recruitment', 'specialist']},
  "it recruitment specialist": {'name': ['it', 'recruitment', 'specialist']},
  "recruitment consultant": {'name': ['recruitment', 'consultant']},
  "technical recruiter": {'name': ['technical', 'recruiter']},
  "production recruiter": {'name': ['production', 'recruiter']},
  "management recruiter": {'name': ['management', 'recruiter']},
  "talent acquisition consultant": {'name': ['talent', 'acquisition', 'consultant']},
  "it recruiter": {'name': ['it', 'recruiter']},
  "executive recruiter": {'name': ['executive', 'recruiter']},
  "talent acquisition": {'name': ['talent', 'acquisition']},
  "talent acquisition recruiter": {'name': ['talent', 'acquisition', 'recruiter']},
  "recruiting manager": {'name': ['recruiting', 'manager']},
  "talent acquisition manager": {'name': ['talent', 'acquisition', 'manager']},
  "sourcer": {'name': ['sourcer']},
  "talent acquisition intern": {'name': ['talent', 'acquisition', 'intern']},
  "campus recruiter": {'name': ['campus', 'recruiter']},
  "staffing specialist": {'name': ['staffing', 'specialist']},
  "junior recruiter": {'name': ['junior', 'recruiter']},
  "entry-level recruiter": {'name': ['entry-level', 'recruiter']},
  "human resource officer": {'name': ['human', 'resource', 'officer']},
  "human resource manager": {'name': ['human', 'resource', 'manager']},
  "human resources manager": {'name': ['human', 'resources', 'manager']},
  "hr coordinator": {'name': ['hr', 'coordinator']},
  "assistant manager": {'name': ['assistant', 'manager']},
  "sales professional": {'name': ['sales', 'professional']},
  "hr generalist": {'name': ['hr', 'generalist']},
  "administrative services specialist": {'name': ['administrative', 'services', 'specialist']},
  "human resource specialist": {'name': ['human', 'resource', 'specialist']},
  "hr data entry": {'name': ['hr', 'data', 'entry']},
  "hr executive": {'name': ['hr', 'executive']},
  "recruitment manager": {'name': ['recruitment', 'manager']},
  "employee engagement specialist": {'name': ['employee', 'engagement', 'specialist']},
  "hr operations manager": {'name': ['hr', 'operations', 'manager']},
  "compensation and benefits specialist": {'name': ['compensation', 'and', 'benefits', 'specialist']},
  "hr business partner": {'name': ['hr', 'business', 'partner']},
  "recruitment coordinator": {'name': ['recruitment', 'coordinator']},
  "hris specialist": {'name': ['hris', 'specialist']},
  "employee relations manager": {'name': ['employee', 'relations', 'manager']},
  "talent management specialist": {'name': ['talent', 'management', 'specialist']},
  "hr consultant": {'name': ['hr', 'consultant']},
  "employee development specialist": {'name': ['employee', 'development', 'specialist']},
  "employee relations specialist": {'name': ['employee', 'relations', 'specialist']},
  "hr compliance specialist": {'name': ['hr', 'compliance', 'specialist']},
  "hr technology specialist": {'name': ['hr', 'technology', 'specialist']},
  "labor relations specialist": {'name': ['labor', 'relations', 'specialist']},
  "training & development specialist": {'name': ['training', '&', 'development', 'specialist']},
  "hr audit & compliance specialist": {'name': ['hr', 'audit', '&', 'compliance', 'specialist']},
  "hr benefits specialist": {'name': ['hr', 'benefits', 'specialist']},
  "hr budget & finance specialist": {'name': ['hr', 'budget', '&', 'finance', 'specialist']},
  "hr change management specialist": {'name': ['hr', 'change', 'management', 'specialist']},
  "hr legal specialist": {'name': ['hr', 'legal', 'specialist']},
  "training specialist": {'name': ['training', 'specialist']},
  "hr director": {'name': ['hr', 'director']},
  "organizational development specialist": {'name': ['organizational', 'development', 'specialist']},
  "office coordinator": {'name': ['office', 'coordinator']},
  "administrative manager": {'name': ['administrative', 'manager']},
  "executive assistant": {'name': ['executive', 'assistant']},
  "operations supervisor": {'name': ['operations', 'supervisor']},
  "administrative officer": {'name': ['administrative', 'officer']},
  "office administrator": {'name': ['office', 'administrator']},
  "administrative coordinator": {'name': ['administrative', 'coordinator']},
  "executive secretary": {'name': ['executive', 'secretary']},
  "office assistant": {'name': ['office', 'assistant']},
  "social media manager": {'name': ['social', 'media', 'manager']},
  "logistics specialist": {'name': ['logistics', 'specialist']},
  "communications officer": {'name': ['communications', 'officer']},
  "procurement officer": {'name': ['procurement', 'officer']},
  "help desk technician": {'name': ['help', 'desk', 'technician']},
  "business advisor": {'name': ['business', 'advisor']},
  "property manager": {'name': ['property', 'manager']},
  "marketing executive": {'name': ['marketing', 'executive']},
  "executive manager": {'name': ['executive', 'manager']},
  "marketing manager": {'name': ['marketing', 'manager']},
  "realtor": {'name': ['realtor']},
  "office operations coordinator": {'name': ['office', 'operations', 'coordinator']},
  "administrative specialist": {'name': ['administrative', 'specialist']},
  "facilities coordinator": {'name': ['facilities', 'coordinator']},
  "office operations manager": {'name': ['office', 'operations', 'manager']},
  "business execution administrator": {'name': ['business', 'execution', 'administrator']},
  "administrative assistant": {'name': ['administrative', 'assistant']},
  "sr. quality technician": {'name': ['sr.', 'quality', 'technician']},
  "procurement specialist": {'name': ['procurement', 'specialist']},
  "grant proposal writer": {'name': ['grant', 'proposal', 'writer']},
  "research assistant": {'name': ['research', 'assistant']},
  "project assistant": {'name': ['project', 'assistant']},
  "project planner": {'name': ['project', 'planner']},
  "operations coordinator": {'name': ['operations', 'coordinator']},
  "training coordinator": {'name': ['training', 'coordinator']},
  "project specialist": {'name': ['project', 'specialist']},
  "project scheduler": {'name': ['project', 'scheduler']},
  "project researcher": {'name': ['project', 'researcher']},
  "service manager": {'name': ['service', 'manager']},
  "clerk": {'name': ['clerk']},
  "retail associate": {'name': ['retail', 'associate']},
  "inventory specialist": {'name': ['inventory', 'specialist']},
  "warehouse associate": {'name': ['warehouse', 'associate']},
  "library assistant": {'name': ['library', 'assistant']},
  "technical support specialist": {'name': ['technical', 'support', 'specialist']},
  "sales associate": {'name': ['sales', 'associate']},
  "human resources assistant": {'name': ['human', 'resources', 'assistant']},
  "data analyst assistant": {'name': ['data', 'analyst', 'assistant']},
  "legal assistant": {'name': ['legal', 'assistant']},
  "maintenance": {'name': ['maintenance']},
  "multimedia content specialist": {'name': ['multimedia', 'content', 'specialist']},
  "communications development specialist": {'name': ['communications', 'development', 'specialist']},
  "marketing campaign specialist": {'name': ['marketing', 'campaign', 'specialist']},
  "creative project specialist": {'name': ['creative', 'project', 'specialist']},
  "promotion specialist": {'name': ['promotion', 'specialist']},
  "visual arts specialist": {'name': ['visual', 'arts', 'specialist']},
  "communications coordinator": {'name': ['communications', 'coordinator']},
  "content distribution specialist": {'name': ['content', 'distribution', 'specialist']},
  "social media engagement specialist": {'name': ['social', 'media', 'engagement', 'specialist']},
  "graphic design specialist": {'name': ['graphic', 'design', 'specialist']},
  "multimedia marketing specialist": {'name': ['multimedia', 'marketing', 'specialist']},
  "pr specialist": {'name': ['pr', 'specialist']},
  "digital media specialist": {'name': ['digital', 'media', 'specialist']},
  "media content specialist": {'name': ['media', 'content', 'specialist']},
  "public affairs specialist": {'name': ['public', 'affairs', 'specialist']},
  "exhibition planning specialist": {'name': ['exhibition', 'planning', 'specialist']},
  "development specialist": {'name': ['development', 'specialist']},
  "multimedia production specialist": {'name': ['multimedia', 'production', 'specialist']},
  "communications specialist": {'name': ['communications', 'specialist']},
  "content strategist": {'name': ['content', 'strategist']},
  "marketing analytics specialist": {'name': ['marketing', 'analytics', 'specialist']},
  "interactive design specialist": {'name': ['interactive', 'design', 'specialist']},
  "creative director": {'name': ['creative', 'director']},
  "digital marketing specialist": {'name': ['digital', 'marketing', 'specialist']},
  "exhibition design specialist": {'name': ['exhibition', 'design', 'specialist']},
  "social media specialist": {'name': ['social', 'media', 'specialist']},
  "copywriter": {'name': ['copywriter']},
  "art director": {'name': ['art', 'director']},
  "video editor": {'name': ['video', 'editor']},
  "exhibit designer": {'name': ['exhibit', 'designer']},
  "exhibition coordinator": {'name': ['exhibition', 'coordinator']},
  "press officer": {'name': ['press', 'officer']},
  "visual merchandiser": {'name': ['visual', 'merchandiser']},
  "user experience designer": {'name': ['user', 'experience', 'designer']},
  "promotions coordinator": {'name': ['promotions', 'coordinator']},
  "copy editor": {'name': ['copy', 'editor']},
  "advertising coordinator": {'name': ['advertising', 'coordinator']},
  "marketing analyst": {'name': ['marketing', 'analyst']},
  "exhibition planner": {'name': ['exhibition', 'planner']},
  "media buyer": {'name': ['media', 'buyer']},
  "press relations officer": {'name': ['press', 'relations', 'officer']},
  "content producer": {'name': ['content', 'producer']},
  "digital media planner": {'name': ['digital', 'media', 'planner']},
  "art curator": {'name': ['art', 'curator']},
  "campaign manager": {'name': ['campaign', 'manager']},
  "media planner": {'name': ['media', 'planner']},
  "exhibition manager": {'name': ['exhibition', 'manager']},
  "public relations coordinator": {'name': ['public', 'relations', 'coordinator']},
  "artistic director": {'name': ['artistic', 'director']},
  "creative strategist": {'name': ['creative', 'strategist']},
  "exhibition designer": {'name': ['exhibition', 'designer']},
  "content creator": {'name': ['content', 'creator']},
  "creative writer": {'name': ['creative', 'writer']},
  "media production manager": {'name': ['media', 'production', 'manager']},
  "production manager": {'name': ['production', 'manager']},
  "multimedia producer": {'name': ['multimedia', 'producer']},
  "pr strategist": {'name': ['pr', 'strategist']},
  "artistic producer": {'name': ['artistic', 'producer']},
  "communications manager": {'name': ['communications', 'manager']},
  "interactive designer": {'name': ['interactive', 'designer']},
  "exhibit coordinator": {'name': ['exhibit', 'coordinator']},
  "community relations specialist": {'name': ['community', 'relations', 'specialist']},
  "multimedia coordinator": {'name': ['multimedia', 'coordinator']},
  "production coordinator": {'name': ['production', 'coordinator']},
  "marketing strategist": {'name': ['marketing', 'strategist']},
  "communications analyst": {'name': ['communications', 'analyst']},
  "media content producer": {'name': ['media', 'content', 'producer']},
  "digital art director": {'name': ['digital', 'art', 'director']},
  "social media analyst": {'name': ['social', 'media', 'analyst']},
  "exhibit manager": {'name': ['exhibit', 'manager']},
  "content marketing specialist": {'name': ['content', 'marketing', 'specialist']},
  "creative development specialist": {'name': ['creative', 'development', 'specialist']},
  "marketing coordinator": {'name': ['marketing', 'coordinator']},
  "interactive media designer": {'name': ['interactive', 'media', 'designer']},
  "visual communication specialist": {'name': ['visual', 'communication', 'specialist']},
  "exhibit development specialist": {'name': ['exhibit', 'development', 'specialist']},
  "advertising manager": {'name': ['advertising', 'manager']},
  "digital art producer": {'name': ['digital', 'art', 'producer']},
  "media strategy specialist": {'name': ['media', 'strategy', 'specialist']},
  "multimedia content producer": {'name': ['multimedia', 'content', 'producer']},
  "communications planner": {'name': ['communications', 'planner']},
  "exhibition marketing specialist": {'name': ['exhibition', 'marketing', 'specialist']},
  "creative content specialist": {'name': ['creative', 'content', 'specialist']},
  "visual merchandising specialist": {'name': ['visual', 'merchandising', 'specialist']},
  "public affairs strategist": {'name': ['public', 'affairs', 'strategist']},
  "media planning specialist": {'name': ['media', 'planning', 'specialist']},
}
