EXPERIENCE_ROLES = {
  "graphic designer": {'name': ['graphic', 'designer']},
  "public relations": {'name': ['public', 'relations']},
  "event planner": {'name': ['event', 'planner']},
  "illustrator": {'name': ['illustrator']},
  "accountant": {'name': ['accountant']},
  "auditor": {'name': ['auditor']},
  "financial manager": {'name': ['financial', 'manager']},
  "bookkeeper": {'name': ['bookkeeper']},
  "financial advisor": {'name': ['financial', 'advisor']},
  "customer service representative": {'name': ['customer', 'service', 'representative']},
  "tutor": {'name': ['tutor']},
  "hotel and restaurant staff": {'name': ['hotel', 'and', 'restaurant', 'staff']},
  "chef": {'name': ['chef']},
  "web developer": {'name': ['web', 'developer']},
  "database administrator": {'name': ['database', 'administrator']},
  "system analyst": {'name': ['system', 'analyst']},
  "application developer": {'name': ['application', 'developer']},
  "developer": {'name': ['developer']},
  "software engineer": {'name': ['software', 'engineer']},
  "medical assistant": {'name': ['medical', 'assistant']},
  "medical doctor": {'name': ['medical', 'doctor']},
  "doctor": {'name': ['doctor']},
  "registered nurse": {'name': ['registered', 'nurse']},
  "pharmacist": {'name': ['pharmacist']},
  "medical laboratory technologist": {'name': ['medical', 'laboratory', 'technologist']},
  "college professor": {'name': ['college', 'professor']},
  "recruiter": {'name': ['recruiter']},
  "hr manager": {'name': ['hr', 'manager']},
  "office manager": {'name': ['office', 'manager']},
  "coordinator": {'name': ['coordinator']},
  "project coordinator": {'name': ['project', 'coordinator']},
  "event coordinator": {'name': ['event', 'coordinator']},
  "event manager": {'name': ['event', 'manager']},
  "community event organizer": {'name': ['community', 'event', 'organizer']},
  "operations manager": {'name': ['operations', 'manager']},
  "logistics strategist": {'name': ['logistics', 'strategist']},
  "entertainment coordinator": {'name': ['entertainment', 'coordinator']},
  "event layout designer": {'name': ['event', 'layout', 'designer']},
  "event marketing strategist": {'name': ['event', 'marketing', 'strategist']},
  "venue contract negotiator": {'name': ['venue', 'contract', 'negotiator']},
  "event supervisor": {'name': ['event', 'supervisor']},
  "event designer": {'name': ['event', 'designer']},
  "marketing specialist": {'name': ['marketing', 'specialist']},
  "visual content creator": {'name': ['visual', 'content', 'creator']},
  "visual strategist": {'name': ['visual', 'strategist']},
  "brand designer": {'name': ['brand', 'designer']},
  "marketing designer": {'name': ['marketing', 'designer']},
  "ui/ux designer": {'name': ['ui/ux', 'designer']},
  "multimedia graphic producer": {'name': ['multimedia', 'graphic', 'producer']},
  "branding specialist": {'name': ['branding', 'specialist']},
  "marketing art producer": {'name': ['marketing', 'art', 'producer']},
  "digital art designer": {'name': ['digital', 'art', 'designer']},
  "icon and logo designer": {'name': ['icon', 'and', 'logo', 'designer']},
  "brand visual designer": {'name': ['brand', 'visual', 'designer']},
  "digital illustration producer": {'name': ['digital', 'illustration', 'producer']},
  "ui design innovator": {'name': ['ui', 'design', 'innovator']},
  "global campaign visual creator": {'name': ['global', 'campaign', 'visual', 'creator']},
  "typography designer": {'name': ['typography', 'designer']},
  "website layout revamper": {'name': ['website', 'layout', 'revamper']},
  "3d modeling animator": {'name': ['3d', 'modeling', 'animator']},
  "custom visual designer": {'name': ['custom', 'visual', 'designer']},
  "visual rebranding strategist": {'name': ['visual', 'rebranding', 'strategist']},
  "packaging design expert": {'name': ['packaging', 'design', 'expert']},
  "social media graphics creator": {'name': ['social', 'media', 'graphics', 'creator']},
  "interactive infographics designer": {'name': ['interactive', 'infographics', 'designer']},
  "ui/ux improvement specialist": {'name': ['ui/ux', 'improvement', 'specialist']},
  "motion graphics producer": {'name': ['motion', 'graphics', 'producer']},
  "visual storytelling strategist": {'name': ['visual', 'storytelling', 'strategist']},
  "design workshop leader": {'name': ['design', 'workshop', 'leader']},
  "mobile ux designer": {'name': ['mobile', 'ux', 'designer']},
  "market research-driven designer": {'name': ['market', 'research-driven', 'designer']},
  "visual-content synchronization collaborator": {'name': ['visual-content', 'synchronization', 'collaborator']},
  "accessibility design specialist": {'name': ['accessibility', 'design', 'specialist']},
  "design process streamliner": {'name': ['design', 'process', 'streamliner']},
  "visual concept translator": {'name': ['visual', 'concept', 'translator']},
  "design thinking prototyper": {'name': ['design', 'thinking', 'prototyper']},
  "user-centered experience designer": {'name': ['user-centered', 'experience', 'designer']},
  "responsive design specialist": {'name': ['responsive', 'design', 'specialist']},
  "usability refinement specialist": {'name': ['usability', 'refinement', 'specialist']},
  "email marketing visual creator": {'name': ['email', 'marketing', 'visual', 'creator']},
  "iconography enhancer": {'name': ['iconography', 'enhancer']},
  "innovative design concept pioneer": {'name': ['innovative', 'design', 'concept', 'pioneer']},
  "human-centric design problem solver": {'name': ['human-centric', 'design', 'problem', 'solver']},
  "pitch deck visual creator": {'name': ['pitch', 'deck', 'visual', 'creator']},
  "design-thinking infuser": {'name': ['design-thinking', 'infuser']},
  "system developer": {'name': ['system', 'developer']},
  "motion graphics integrator": {'name': ['motion', 'graphics', 'integrator']},
  "a/b testing designer": {'name': ['a/b', 'testing', 'designer']},
  "gamification interface implementer": {'name': ['gamification', 'interface', 'implementer']},
  "website navigation redesigner": {'name': ['website', 'navigation', 'redesigner']},
  "creative brainstorming leader": {'name': ['creative', 'brainstorming', 'leader']},
  "eco-friendly print material optimizer": {'name': ['eco-friendly', 'print', 'material', 'optimizer']},
  "social cause visual campaign creator": {'name': ['social', 'cause', 'visual', 'campaign', 'creator']},
  "interactive prototype creator": {'name': ['interactive', 'prototype', 'creator']},
  "custom illustration brand enhancer": {'name': ['custom', 'illustration', 'brand', 'enhancer']},
  "color psychology visual designer": {'name': ['color', 'psychology', 'visual', 'designer']},
  "accessibility-compliant website layout revamper": {'name': ['accessibility-compliant', 'website', 'layout', 'revamper']},
  "innovative typography designer": {'name': ['innovative', 'typography', 'designer']},
  "animated infographics creator": {'name': ['animated', 'infographics', 'creator']},
  "user interview collaborator": {'name': ['user', 'interview', 'collaborator']},
  "photo manipulation specialist": {'name': ['photo', 'manipulation', 'specialist']},
  "brand narrative visual designer": {'name': ['brand', 'narrative', 'visual', 'designer']},
  "social media engagement contributor": {'name': ['social', 'media', 'engagement', 'contributor']},
  "startup pitch deck creator": {'name': ['startup', 'pitch', 'deck', 'creator']},
  "data visualization designer": {'name': ['data', 'visualization', 'designer']},
  "interactive content producer": {'name': ['interactive', 'content', 'producer']},
  "product launch brand visualizer": {'name': ['product', 'launch', 'brand', 'visualizer']},
  "visual identity system executor": {'name': ['visual', 'identity', 'system', 'executor']},
  "grid layout designer": {'name': ['grid', 'layout', 'designer']},
  "editorial illustration enhancer": {'name': ['editorial', 'illustration', 'enhancer']},
  "business goal translator": {'name': ['business', 'goal', 'translator']},
  "stand-out packaging designer": {'name': ['stand-out', 'packaging', 'designer']},
  "user persona and journey mapper": {'name': ['user', 'persona', 'and', 'journey', 'mapper']},
  "responsive web designer": {'name': ['responsive', 'web', 'designer']},
  "usability tester": {'name': ['usability', 'tester']},
  "custom graphics and illustrations designer": {'name': ['custom', 'graphics', 'and', 'illustrations', 'designer']},
  "design thinking ui/ux problem solver": {'name': ['design', 'thinking', 'ui/ux', 'problem', 'solver']},
  "cross-functional design integrator": {'name': ['cross-functional', 'design', 'integrator']},
  "packaging designer": {'name': ['packaging', 'designer']},
  "visual storyteller": {'name': ['visual', 'storyteller']},
  "visual branding designer": {'name': ['visual', 'branding', 'designer']},
  "visual brand strategist": {'name': ['visual', 'brand', 'strategist']},
  "marketing design specialist": {'name': ['marketing', 'design', 'specialist']},
  "digital marketing visual designer": {'name': ['digital', 'marketing', 'visual', 'designer']},
  "multimedia visual designer": {'name': ['multimedia', 'visual', 'designer']},
  "interactive visual designer": {'name': ['interactive', 'visual', 'designer']},
  "marketing visual designer": {'name': ['marketing', 'visual', 'designer']},
  "marketing visualizer": {'name': ['marketing', 'visualizer']},
  "visual media specialist": {'name': ['visual', 'media', 'specialist']},
  "brand strategist": {'name': ['brand', 'strategist']},
  "design director": {'name': ['design', 'director']},
  "multimedia artist": {'name': ['multimedia', 'artist']},
  "visual design specialist": {'name': ['visual', 'design', 'specialist']},
  "visual content producer": {'name': ['visual', 'content', 'producer']},
  "visual designer": {'name': ['visual', 'designer']},
  "graphic content creator": {'name': ['graphic', 'content', 'creator']},
  "visual content designer": {'name': ['visual', 'content', 'designer']},
  "brand identity designer": {'name': ['brand', 'identity', 'designer']},
  "concept artist": {'name': ['concept', 'artist']},
  "visual branding specialist": {'name': ['visual', 'branding', 'specialist']},
  "ui/ux visual designer": {'name': ['ui/ux', 'visual', 'designer']},
  "brand visualizer": {'name': ['brand', 'visualizer']},
  "digital artist": {'name': ['digital', 'artist']},
  "multimedia designer": {'name': ['multimedia', 'designer']},
  "social media visual designer": {'name': ['social', 'media', 'visual', 'designer']},
  "web visual designer": {'name': ['web', 'visual', 'designer']},
  "mobile app visual artist": {'name': ['mobile', 'app', 'visual', 'artist']},
  "user interface designer": {'name': ['user', 'interface', 'designer']},
  "packaging visual designer": {'name': ['packaging', 'visual', 'designer']},
  "motion graphics designer": {'name': ['motion', 'graphics', 'designer']},
  "marketing graphic designer": {'name': ['marketing', 'graphic', 'designer']},
  "junior graphic designer": {'name': ['junior', 'graphic', 'designer']},
  "media content creator": {'name': ['media', 'content', 'creator']},
  "social media pr specialist": {'name': ['social', 'media', 'pr', 'specialist']},
  "pr assistant": {'name': ['pr', 'assistant']},
  "pr support assistant": {'name': ['pr', 'support', 'assistant']},
  "digital pr specialist": {'name': ['digital', 'pr', 'specialist']},
  "press relations manager": {'name': ['press', 'relations', 'manager']},
  "pr analyst": {'name': ['pr', 'analyst']},
  "pr support specialist": {'name': ['pr', 'support', 'specialist']},
  "influencer relations specialist": {'name': ['influencer', 'relations', 'specialist']},
  "media outreach assistant": {'name': ['media', 'outreach', 'assistant']},
  "media relations specialist": {'name': ['media', 'relations', 'specialist']},
  "pr campaign assistant": {'name': ['pr', 'campaign', 'assistant']},
  "online pr specialist": {'name': ['online', 'pr', 'specialist']},
  "press release specialist": {'name': ['press', 'release', 'specialist']},
  "storytelling content creator": {'name': ['storytelling', 'content', 'creator']},
  "digital pr strategist": {'name': ['digital', 'pr', 'strategist']},
  "nonprofit communication strategist": {'name': ['nonprofit', 'communication', 'strategist']},
  "brand narrative strategist": {'name': ['brand', 'narrative', 'strategist']},
  "senior accountant": {'name': ['senior', 'accountant']},
  "financial analyst": {'name': ['financial', 'analyst']},
  "staff accountant": {'name': ['staff', 'accountant']},
  "cost accountant": {'name': ['cost', 'accountant']},
  "tax accountant": {'name': ['tax', 'accountant']},
  "forensic accountant": {'name': ['forensic', 'accountant']},
  "internal auditor": {'name': ['internal', 'auditor']},
  "management accountant": {'name': ['management', 'accountant']},
  "project accountant": {'name': ['project', 'accountant']},
  "government auditor": {'name': ['government', 'auditor']},
  "financial controler": {'name': ['financial', 'controler']},
  "junior accountant": {'name': ['junior', 'accountant']},
  "external auditor": {'name': ['external', 'auditor']},
  "budget analyst": {'name': ['budget', 'analyst']},
  "tax consultant": {'name': ['tax', 'consultant']},
  "cost control analyst": {'name': ['cost', 'control', 'analyst']},
  "financial reporting analyst": {'name': ['financial', 'reporting', 'analyst']},
  "risk management specialist": {'name': ['risk', 'management', 'specialist']},
  "senior auditor": {'name': ['senior', 'auditor']},
  "tax analyst": {'name': ['tax', 'analyst']},
  "financial planner": {'name': ['financial', 'planner']},
  "cost analyst": {'name': ['cost', 'analyst']},
  "senior tax accountant": {'name': ['senior', 'tax', 'accountant']},
  "audit manager": {'name': ['audit', 'manager']},
  "corporate accountant": {'name': ['corporate', 'accountant']},
  "treasury analyst": {'name': ['treasury', 'analyst']},
  "junior auditor": {'name': ['junior', 'auditor']},
  "senior cost accountant": {'name': ['senior', 'cost', 'accountant']},
  "government accountant": {'name': ['government', 'accountant']},
  "compliance auditor": {'name': ['compliance', 'auditor']},
  "investment accountant": {'name': ['investment', 'accountant']},
  "senior treasury analyst": {'name': ['senior', 'treasury', 'analyst']},
  "financial systems analyst": {'name': ['financial', 'systems', 'analyst']},
  "tax manager": {'name': ['tax', 'manager']},
  "revenue accountant": {'name': ['revenue', 'accountant']},
  "financial controller": {'name': ['financial', 'controller']},
  "budget manager": {'name': ['budget', 'manager']},
  "corporate treasurer": {'name': ['corporate', 'treasurer']},
  "financial system analyst": {'name': ['financial', 'system', 'analyst']},
  "risk manager": {'name': ['risk', 'manager']},
  "systems manager": {'name': ['systems', 'manager']},
  "trading manager": {'name': ['trading', 'manager']},
  "finance manager": {'name': ['finance', 'manager']},
  "compliance manager": {'name': ['compliance', 'manager']},
  "financial risk manager": {'name': ['financial', 'risk', 'manager']},
  "junior bookkeeper": {'name': ['junior', 'bookkeeper']},
  "accounts assistant": {'name': ['accounts', 'assistant']},
  "assistant bookkeeper": {'name': ['assistant', 'bookkeeper']},
  "bookkeeping specialist": {'name': ['bookkeeping', 'specialist']},
  "accounting assistant": {'name': ['accounting', 'assistant']},
  "entry level bookkeeper": {'name': ['entry', 'level', 'bookkeeper']},
  "bookkeeping analyst": {'name': ['bookkeeping', 'analyst']},
  "bookkeeping administrator": {'name': ['bookkeeping', 'administrator']},
  "bookkeeping technician": {'name': ['bookkeeping', 'technician']},
  "senior bookkeeping specialist": {'name': ['senior', 'bookkeeping', 'specialist']},
  "accounts payable specialist": {'name': ['accounts', 'payable', 'specialist']},
  "junior bookkeeping assistant": {'name': ['junior', 'bookkeeping', 'assistant']},
  "consultant": {'name': ['consultant']},
  "accounts recievable specialist": {'name': ['accounts', 'recievable', 'specialist']},
  "accounting administrator": {'name': ['accounting', 'administrator']},
  "junior financial advisor": {'name': ['junior', 'financial', 'advisor']},
  "financial consultant": {'name': ['financial', 'consultant']},
  "management advisor": {'name': ['management', 'advisor']},
  "retirement planning specialist": {'name': ['retirement', 'planning', 'specialist']},
  "investment advisor": {'name': ['investment', 'advisor']},
  "estate planning advisor": {'name': ['estate', 'planning', 'advisor']},
  "insurance advisor": {'name': ['insurance', 'advisor']},
  "tax planning specialist": {'name': ['tax', 'planning', 'specialist']},
  "debt management advisor": {'name': ['debt', 'management', 'advisor']},
  "real estate investment advisor": {'name': ['real', 'estate', 'investment', 'advisor']},
  "college planning specialist": {'name': ['college', 'planning', 'specialist']},
  "budgeting advisor": {'name': ['budgeting', 'advisor']},
  "business financial advisor": {'name': ['business', 'financial', 'advisor']},
  "sustainable investing advisor": {'name': ['sustainable', 'investing', 'advisor']},
  "financial strategist": {'name': ['financial', 'strategist']},
  "senior financial advisor": {'name': ['senior', 'financial', 'advisor']},
  "philantrophic advisor": {'name': ['philantrophic', 'advisor']},
  "behavioral finance specialist": {'name': ['behavioral', 'finance', 'specialist']},
  "alternative investments advisor": {'name': ['alternative', 'investments', 'advisor']},
  "financial wellness coach": {'name': ['financial', 'wellness', 'coach']},
  "digital financial advisor": {'name': ['digital', 'financial', 'advisor']},
  "governance advisor": {'name': ['governance', 'advisor']},
  "financial education specialist": {'name': ['financial', 'education', 'specialist']},
  "financial technology advisor": {'name': ['financial', 'technology', 'advisor']},
  "financial coaching specialist": {'name': ['financial', 'coaching', 'specialist']},
  "sustainable finance advisor": {'name': ['sustainable', 'finance', 'advisor']},
  "student financial advisor": {'name': ['student', 'financial', 'advisor']},
  "behavioral coaching specialist": {'name': ['behavioral', 'coaching', 'specialist']},
  "small business financing advisor": {'name': ['small', 'business', 'financing', 'advisor']},
  "retirement health specialist": {'name': ['retirement', 'health', 'specialist']},
  "cryptocurrency investment advisor": {'name': ['cryptocurrency', 'investment', 'advisor']},
  "executive financial advisor": {'name': ['executive', 'financial', 'advisor']},
  "personal finance educator": {'name': ['personal', 'finance', 'educator']},
  "venture capital advisor": {'name': ['venture', 'capital', 'advisor']},
  "real estate tax planning specialist": {'name': ['real', 'estate', 'tax', 'planning', 'specialist']},
  "payroll accountant": {'name': ['payroll', 'accountant']},
  "compliance officer": {'name': ['compliance', 'officer']},
  "international tax specialist": {'name': ['international', 'tax', 'specialist']},
  "forensic auditor": {'name': ['forensic', 'auditor']},
  "inventory accountant": {'name': ['inventory', 'accountant']},
  "financial risk analyst": {'name': ['financial', 'risk', 'analyst']},
  "real estate accountant": {'name': ['real', 'estate', 'accountant']},
  "sustainability accountant": {'name': ['sustainability', 'accountant']},
  "nonprofit accountant": {'name': ['nonprofit', 'accountant']},
  "financial modeling specialist": {'name': ['financial', 'modeling', 'specialist']},
  "retail accountant": {'name': ['retail', 'accountant']},
  "corporate tax advisor": {'name': ['corporate', 'tax', 'advisor']},
  "treasury accountant": {'name': ['treasury', 'accountant']},
  "financial systems auditor": {'name': ['financial', 'systems', 'auditor']},
  "derivatives accountant": {'name': ['derivatives', 'accountant']},
  "mergers and acquisitions accountant": {'name': ['mergers', 'and', 'acquisitions', 'accountant']},
  "international auditor": {'name': ['international', 'auditor']},
  "cost estimation specialist": {'name': ['cost', 'estimation', 'specialist']},
  "financial software implementation specialist": {'name': ['financial', 'software', 'implementation', 'specialist']},
  "financial compliance officer": {'name': ['financial', 'compliance', 'officer']},
  "cryptocurrency accountant": {'name': ['cryptocurrency', 'accountant']},
  "hedge fund accountant": {'name': ['hedge', 'fund', 'accountant']},
  "government grant accountant": {'name': ['government', 'grant', 'accountant']},
  "financial auditor": {'name': ['financial', 'auditor']},
  "sustainability reporting specialist": {'name': ['sustainability', 'reporting', 'specialist']},
  "private equity accountant": {'name': ['private', 'equity', 'accountant']},
  "financial systems integration specialist": {'name': ['financial', 'systems', 'integration', 'specialist']},
  "business valuation specialist": {'name': ['business', 'valuation', 'specialist']},
  "taxation manager": {'name': ['taxation', 'manager']},
  "budgeting manager": {'name': ['budgeting', 'manager']},
  "banking manager": {'name': ['banking', 'manager']},
  "entry-level bookkeeper": {'name': ['entry-level', 'bookkeeper']},
  "senior bookkeeper": {'name': ['senior', 'bookkeeper']},
  "corporate bookkeeper": {'name': ['corporate', 'bookkeeper']},
  "freelance bookkeeper": {'name': ['freelance', 'bookkeeper']},
  "virtual bookkeeper": {'name': ['virtual', 'bookkeeper']},
  "certified bookkeeper": {'name': ['certified', 'bookkeeper']},
  "full-charge bookkeeper": {'name': ['full-charge', 'bookkeeper']},
  "senior accounting specialist": {'name': ['senior', 'accounting', 'specialist']},
  "accounting manager": {'name': ['accounting', 'manager']},
  "bookkeeping manager": {'name': ['bookkeeping', 'manager']},
  "bookkeeping system analyst": {'name': ['bookkeeping', 'system', 'analyst']},
  "senior financial analyst": {'name': ['senior', 'financial', 'analyst']},
  "bookkeeping and business analyst": {'name': ['bookkeeping', 'and', 'business', 'analyst']},
  "freelance accounting specialist": {'name': ['freelance', 'accounting', 'specialist']},
  "small business bookkeeper": {'name': ['small', 'business', 'bookkeeper']},
  "tax and bookkeeping specialist": {'name': ['tax', 'and', 'bookkeeping', 'specialist']},
  "virtual bookkeeping assistant": {'name': ['virtual', 'bookkeeping', 'assistant']},
  "corporate finance analyst": {'name': ['corporate', 'finance', 'analyst']},
  "accounting and payroll specialist": {'name': ['accounting', 'and', 'payroll', 'specialist']},
  "financial data analyst": {'name': ['financial', 'data', 'analyst']},
  "senior accounting analyst": {'name': ['senior', 'accounting', 'analyst']},
  "bookkeeping and erp specialist": {'name': ['bookkeeping', 'and', 'erp', 'specialist']},
  "wealth management associate": {'name': ['wealth', 'management', 'associate']},
  "investment strategist": {'name': ['investment', 'strategist']},
  "retirement income planner": {'name': ['retirement', 'income', 'planner']},
  "chartered financial analyst": {'name': ['chartered', 'financial', 'analyst']},
  "family wealth advisor": {'name': ['family', 'wealth', 'advisor']},
  "financial literacy advocate": {'name': ['financial', 'literacy', 'advocate']},
  "business succession planner": {'name': ['business', 'succession', 'planner']},
  "certified investment advisor": {'name': ['certified', 'investment', 'advisor']},
  "financial planning specialist": {'name': ['financial', 'planning', 'specialist']},
  "junior investment advisor": {'name': ['junior', 'investment', 'advisor']},
  "wealth preservation advisor": {'name': ['wealth', 'preservation', 'advisor']},
  "philanthropic financial advisor": {'name': ['philanthropic', 'financial', 'advisor']},
  "behavioral finance analyst": {'name': ['behavioral', 'finance', 'analyst']},
  "retirement income strategist": {'name': ['retirement', 'income', 'strategist']},
  "financial wellness specialist": {'name': ['financial', 'wellness', 'specialist']},
  "international wealth advisor": {'name': ['international', 'wealth', 'advisor']},
  "tax efficiency specialist": {'name': ['tax', 'efficiency', 'specialist']},
  "retirement lifestyle planner": {'name': ['retirement', 'lifestyle', 'planner']},
  "corporate financial wellness advisor": {'name': ['corporate', 'financial', 'wellness', 'advisor']},
  "financial innovation specialist": {'name': ['financial', 'innovation', 'specialist']},
  "philanthropy advisor": {'name': ['philanthropy', 'advisor']},
  "behavioral wealth advisor": {'name': ['behavioral', 'wealth', 'advisor']},
  "tech-driven financial advisor": {'name': ['tech-driven', 'financial', 'advisor']},
  "retirement income specialist": {'name': ['retirement', 'income', 'specialist']},
  "sustainable investment advisor": {'name': ['sustainable', 'investment', 'advisor']},
  "corporate retirement specialist": {'name': ['corporate', 'retirement', 'specialist']},
  "investment innovation advisor": {'name': ['investment', 'innovation', 'advisor']},
  "family office advisor": {'name': ['family', 'office', 'advisor']},
  "global investment strategist": {'name': ['global', 'investment', 'strategist']},
  "senior financial auditor": {'name': ['senior', 'financial', 'auditor']},
  "tax auditor": {'name': ['tax', 'auditor']},
  "risk management auditor": {'name': ['risk', 'management', 'auditor']},
  "internal controls auditor": {'name': ['internal', 'controls', 'auditor']},
  "audit quality assurance analyst": {'name': ['audit', 'quality', 'assurance', 'analyst']},
  "it auditor": {'name': ['it', 'auditor']},
  "senior audit analyst": {'name': ['senior', 'audit', 'analyst']},
  "financial reporting auditor": {'name': ['financial', 'reporting', 'auditor']},
  "external financial auditor": {'name': ['external', 'financial', 'auditor']},
  "financial compliance analyst": {'name': ['financial', 'compliance', 'analyst']},
  "audit director": {'name': ['audit', 'director']},
  "tax compliance auditor": {'name': ['tax', 'compliance', 'auditor']},
  "fraud risk auditor": {'name': ['fraud', 'risk', 'auditor']},
  "data privacy auditor": {'name': ['data', 'privacy', 'auditor']},
  "financial modeling auditor": {'name': ['financial', 'modeling', 'auditor']},
  "supply chain auditor": {'name': ['supply', 'chain', 'auditor']},
  "it security auditor": {'name': ['it', 'security', 'auditor']},
  "sustainability auditor": {'name': ['sustainability', 'auditor']},
  "corporate governance auditor": {'name': ['corporate', 'governance', 'auditor']},
  "cost accounting auditor": {'name': ['cost', 'accounting', 'auditor']},
  "international tax auditor": {'name': ['international', 'tax', 'auditor']},
  "quality management auditor": {'name': ['quality', 'management', 'auditor']},
  "corporate compliance auditor": {'name': ['corporate', 'compliance', 'auditor']},
  "enterprise risk auditor": {'name': ['enterprise', 'risk', 'auditor']},
  "financial planning auditor": {'name': ['financial', 'planning', 'auditor']},
  "project management auditor": {'name': ['project', 'management', 'auditor']},
  "ethics and compliance auditor": {'name': ['ethics', 'and', 'compliance', 'auditor']},
  "data analytics auditor": {'name': ['data', 'analytics', 'auditor']},
  "business process auditor": {'name': ['business', 'process', 'auditor']},
  "outsourcing risk auditor": {'name': ['outsourcing', 'risk', 'auditor']},
  "cybersecurity compliance auditor": {'name': ['cybersecurity', 'compliance', 'auditor']},
  "change management auditor": {'name': ['change', 'management', 'auditor']},
  "mergers and acquisitions auditor": {'name': ['mergers', 'and', 'acquisitions', 'auditor']},
  "international financial auditor": {'name': ['international', 'financial', 'auditor']},
  "sustainability risk auditor": {'name': ['sustainability', 'risk', 'auditor']},
  "operational efficiency auditor": {'name': ['operational', 'efficiency', 'auditor']},
  "financial derivatives auditor": {'name': ['financial', 'derivatives', 'auditor']},
  "cultural compliance auditor": {'name': ['cultural', 'compliance', 'auditor']},
  "nonprofit financial auditor": {'name': ['nonprofit', 'financial', 'auditor']},
  "sustainability reporting auditor": {'name': ['sustainability', 'reporting', 'auditor']},
  "cybersecurity threat auditor": {'name': ['cybersecurity', 'threat', 'auditor']},
  "global compliance auditor": {'name': ['global', 'compliance', 'auditor']},
  "esg reporting auditor": {'name': ['esg', 'reporting', 'auditor']},
  "lean management auditor": {'name': ['lean', 'management', 'auditor']},
  "healthcare compliance auditor": {'name': ['healthcare', 'compliance', 'auditor']},
  "it governance auditor": {'name': ['it', 'governance', 'auditor']},
  "social impact auditor": {'name': ['social', 'impact', 'auditor']},
  "forensic accounting investigator": {'name': ['forensic', 'accounting', 'investigator']},
  "business continuity auditor": {'name': ['business', 'continuity', 'auditor']},
  "real estate investment auditor": {'name': ['real', 'estate', 'investment', 'auditor']},
  "regulatory compliance auditor": {'name': ['regulatory', 'compliance', 'auditor']},
  "cybersecurity incident responder": {'name': ['cybersecurity', 'incident', 'responder']},
  "diversity, equity, and inclusion auditor": {'name': ['diversity', 'equity', 'and', 'inclusion', 'auditor']},
  "continuous auditing specialist": {'name': ['continuous', 'auditing', 'specialist']},
  "product lifecycle auditor": {'name': ['product', 'lifecycle', 'auditor']},
  "behavioral economics auditor": {'name': ['behavioral', 'economics', 'auditor']},
  "enterprise architecture auditor": {'name': ['enterprise', 'architecture', 'auditor']},
  "supply chain risk auditor": {'name': ['supply', 'chain', 'risk', 'auditor']},
  "artificial intelligence auditor": {'name': ['artificial', 'intelligence', 'auditor']},
  "conflict of interest auditor": {'name': ['conflict', 'of', 'interest', 'auditor']},
  "blockchain compliance auditor": {'name': ['blockchain', 'compliance', 'auditor']},
  "corporate social responsibility auditor": {'name': ['corporate', 'social', 'responsibility', 'auditor']},
  "data governance auditor": {'name': ['data', 'governance', 'auditor']},
  "internal control auditor": {'name': ['internal', 'control', 'auditor']},
  "cryptocurrency auditor": {'name': ['cryptocurrency', 'auditor']},
  "employee benefits auditor": {'name': ['employee', 'benefits', 'auditor']},
  "artificial intelligence ethics auditor": {'name': ['artificial', 'intelligence', 'ethics', 'auditor']},
  "compliance monitoring auditor": {'name': ['compliance', 'monitoring', 'auditor']},
  "environmental impact auditor": {'name': ['environmental', 'impact', 'auditor']},
  "tax strategy auditor": {'name': ['tax', 'strategy', 'auditor']},
  "cloud security auditor": {'name': ['cloud', 'security', 'auditor']},
  "public sector auditor": {'name': ['public', 'sector', 'auditor']},
  "financial compliance auditor": {'name': ['financial', 'compliance', 'auditor']},
  "social media compliance auditor": {'name': ['social', 'media', 'compliance', 'auditor']},
  "global tax compliance auditor": {'name': ['global', 'tax', 'compliance', 'auditor']},
  "business valuation auditor": {'name': ['business', 'valuation', 'auditor']},
  "it risk management auditor": {'name': ['it', 'risk', 'management', 'auditor']},
  "hospitality industry auditor": {'name': ['hospitality', 'industry', 'auditor']},
  "data privacy compliance auditor": {'name': ['data', 'privacy', 'compliance', 'auditor']},
  "innovation audit specialist": {'name': ['innovation', 'audit', 'specialist']},
  "pharmaceutical compliance auditor": {'name': ['pharmaceutical', 'compliance', 'auditor']},
  "international trade auditor": {'name': ['international', 'trade', 'auditor']},
  "marketing compliance auditor": {'name': ['marketing', 'compliance', 'auditor']},
  "agile project management auditor": {'name': ['agile', 'project', 'management', 'auditor']},
  "telecommunications audit specialist": {'name': ['telecommunications', 'audit', 'specialist']},
  "customer sales representative": {'name': ['customer', 'sales', 'representative']},
  "customer service": {'name': ['customer', 'service']},
  "support representative": {'name': ['support', 'representative']},
  "csr specialist": {'name': ['csr', 'specialist']},
  "client support": {'name': ['client', 'support']},
  "customer representative": {'name': ['customer', 'representative']},
  "service agent": {'name': ['service', 'agent']},
  "customer advocate": {'name': ['customer', 'advocate']},
  "support associate": {'name': ['support', 'associate']},
  "client relations": {'name': ['client', 'relations']},
  "customer service specialist": {'name': ['customer', 'service', 'specialist']},
  "support rep": {'name': ['support', 'rep']},
  "service specialist": {'name': ['service', 'specialist']},
  "technical support agent": {'name': ['technical', 'support', 'agent']},
  "billing specialist": {'name': ['billing', 'specialist']},
  "email support specialist": {'name': ['email', 'support', 'specialist']},
  "sales support associate": {'name': ['sales', 'support', 'associate']},
  "technical helpdesk agent": {'name': ['technical', 'helpdesk', 'agent']},
  "social media support": {'name': ['social', 'media', 'support']},
  "escalation support agent": {'name': ['escalation', 'support', 'agent']},
  "remote support specialist": {'name': ['remote', 'support', 'specialist']},
  "product knowledge specialist": {'name': ['product', 'knowledge', 'specialist']},
  "customer retention specialist": {'name': ['customer', 'retention', 'specialist']},
  "technical customer support": {'name': ['technical', 'customer', 'support']},
  "order processing specialist": {'name': ['order', 'processing', 'specialist']},
  "chat support representative": {'name': ['chat', 'support', 'representative']},
  "product support specialist": {'name': ['product', 'support', 'specialist']},
  "helpdesk specialist": {'name': ['helpdesk', 'specialist']},
  "inbound calls specialist": {'name': ['inbound', 'calls', 'specialist']},
  "product support analyst": {'name': ['product', 'support', 'analyst']},
  "vip customer support": {'name': ['vip', 'customer', 'support']},
  "escalation support specialist": {'name': ['escalation', 'support', 'specialist']},
  "remote technical support": {'name': ['remote', 'technical', 'support']},
  "technical trainer": {'name': ['technical', 'trainer']},
  "order fulfillment specialist": {'name': ['order', 'fulfillment', 'specialist']},
  "chatbot support specialist": {'name': ['chatbot', 'support', 'specialist']},
  "quality assurance analyst": {'name': ['quality', 'assurance', 'analyst']},
  "fraud prevention specialist": {'name': ['fraud', 'prevention', 'specialist']},
  "international customer support": {'name': ['international', 'customer', 'support']},
  "technical documentation specialist": {'name': ['technical', 'documentation', 'specialist']},
  "e-commerce customer support": {'name': ['e-commerce', 'customer', 'support']},
  "video support specialist": {'name': ['video', 'support', 'specialist']},
  "customer analytics specialist": {'name': ['customer', 'analytics', 'specialist']},
  "multichannel support agent": {'name': ['multichannel', 'support', 'agent']},
  "it service desk analyst": {'name': ['it', 'service', 'desk', 'analyst']},
  "customer feedback analyst": {'name': ['customer', 'feedback', 'analyst']},
  "product feedback specialist": {'name': ['product', 'feedback', 'specialist']},
  "ai chatbot trainer": {'name': ['ai', 'chatbot', 'trainer']},
  "vip tech support specialist": {'name': ['vip', 'tech', 'support', 'specialist']},
  "billing dispute specialist": {'name': ['billing', 'dispute', 'specialist']},
  "social media support analyst": {'name': ['social', 'media', 'support', 'analyst']},
  "support analyst": {'name': ['support', 'analyst']},
  "customer onboarding specialist": {'name': ['customer', 'onboarding', 'specialist']},
  "international technical support": {'name': ['international', 'technical', 'support']},
  "customer satisfaction analyst": {'name': ['customer', 'satisfaction', 'analyst']},
  "customer engagement specialist": {'name': ['customer', 'engagement', 'specialist']},
  "technical documentation writer": {'name': ['technical', 'documentation', 'writer']},
  "order tracking specialist": {'name': ['order', 'tracking', 'specialist']},
  "video call support specialist": {'name': ['video', 'call', 'support', 'specialist']},
  "customer data privacy specialist": {'name': ['customer', 'data', 'privacy', 'specialist']},
  "multilingual customer support": {'name': ['multilingual', 'customer', 'support']},
  "ai customer support specialist": {'name': ['ai', 'customer', 'support', 'specialist']},
  "data analyst - customer support": {'name': ['data', 'analyst', '-', 'customer', 'support']},
  "customer advocacy specialist": {'name': ['customer', 'advocacy', 'specialist']},
  "in-app support specialist": {'name': ['in-app', 'support', 'specialist']},
  "customer loyalty specialist": {'name': ['customer', 'loyalty', 'specialist']},
  "voice support specialist": {'name': ['voice', 'support', 'specialist']},
  "gamification support specialist": {'name': ['gamification', 'support', 'specialist']},
  "technical sales support": {'name': ['technical', 'sales', 'support']},
  "diversity and inclusion support": {'name': ['diversity', 'and', 'inclusion', 'support']},
  "customer wellness specialist": {'name': ['customer', 'wellness', 'specialist']},
  "voice of customer analyst": {'name': ['voice', 'of', 'customer', 'analyst']},
  "customer journey specialist": {'name': ['customer', 'journey', 'specialist']},
  "preschool tutor": {'name': ['preschool', 'tutor']},
  "early education tutor": {'name': ['early', 'education', 'tutor']},
  "preschool educator": {'name': ['preschool', 'educator']},
  "early learning specialist": {'name': ['early', 'learning', 'specialist']},
  "play-based learning tutor": {'name': ['play-based', 'learning', 'tutor']},
  "kindergarten tutor": {'name': ['kindergarten', 'tutor']},
  "child development tutor": {'name': ['child', 'development', 'tutor']},
  "learning through play tutor": {'name': ['learning', 'through', 'play', 'tutor']},
  "creative curriculum tutor": {'name': ['creative', 'curriculum', 'tutor']},
  "early childhood specialist": {'name': ['early', 'childhood', 'specialist']},
  "interactive learning tutor": {'name': ['interactive', 'learning', 'tutor']},
  "early literacy tutor": {'name': ['early', 'literacy', 'tutor']},
  "inclusive education tutor": {'name': ['inclusive', 'education', 'tutor']},
  "technology in education tutor": {'name': ['technology', 'in', 'education', 'tutor']},
  "classroom management tutor": {'name': ['classroom', 'management', 'tutor']},
  "interactive education tutor": {'name': ['interactive', 'education', 'tutor']},
  "montessori tutor": {'name': ['montessori', 'tutor']},
  "stem education tutor": {'name': ['stem', 'education', 'tutor']},
  "individualized instruction tutor": {'name': ['individualized', 'instruction', 'tutor']},
  "outdoor education tutor": {'name': ['outdoor', 'education', 'tutor']},
  "special education tutor": {'name': ['special', 'education', 'tutor']},
  "project-based learning tutor": {'name': ['project-based', 'learning', 'tutor']},
  "inclusive learning tutor": {'name': ['inclusive', 'learning', 'tutor']},
  "mindfulness education tutor": {'name': ['mindfulness', 'education', 'tutor']},
  "cooperative learning tutor": {'name': ['cooperative', 'learning', 'tutor']},
  "differentiated instruction tutor": {'name': ['differentiated', 'instruction', 'tutor']},
  "outdoor science education tutor": {'name': ['outdoor', 'science', 'education', 'tutor']},
  "literacy intervention tutor": {'name': ['literacy', 'intervention', 'tutor']},
  "language development tutor": {'name': ['language', 'development', 'tutor']},
  "collaborative learning tutor": {'name': ['collaborative', 'learning', 'tutor']},
  "music education tutor": {'name': ['music', 'education', 'tutor']},
  "esl tutor": {'name': ['esl', 'tutor']},
  "reading specialist tutor": {'name': ['reading', 'specialist', 'tutor']},
  "visual arts education tutor": {'name': ['visual', 'arts', 'education', 'tutor']},
  "math enrichment tutor": {'name': ['math', 'enrichment', 'tutor']},
  "virtual learning tutor": {'name': ['virtual', 'learning', 'tutor']},
  "science exploration tutor": {'name': ['science', 'exploration', 'tutor']},
  "social studies tutor": {'name': ['social', 'studies', 'tutor']},
  "time management tutor": {'name': ['time', 'management', 'tutor']},
  "test preparation tutor": {'name': ['test', 'preparation', 'tutor']},
  "language arts tutor": {'name': ['language', 'arts', 'tutor']},
  "stem enrichment tutor": {'name': ['stem', 'enrichment', 'tutor']},
  "problem-solving tutor": {'name': ['problem-solving', 'tutor']},
  "leadership development tutor": {'name': ['leadership', 'development', 'tutor']},
  "critical thinking tutor": {'name': ['critical', 'thinking', 'tutor']},
  "language development specialist": {'name': ['language', 'development', 'specialist']},
  "financial literacy tutor": {'name': ['financial', 'literacy', 'tutor']},
  "coding education tutor": {'name': ['coding', 'education', 'tutor']},
  "environmental education tutor": {'name': ['environmental', 'education', 'tutor']},
  "health and wellness tutor": {'name': ['health', 'and', 'wellness', 'tutor']},
  "multilingual education tutor": {'name': ['multilingual', 'education', 'tutor']},
  "debate and public speaking tutor": {'name': ['debate', 'and', 'public', 'speaking', 'tutor']},
  "personal finance tutor": {'name': ['personal', 'finance', 'tutor']},
  "creative writing tutor": {'name': ['creative', 'writing', 'tutor']},
  "yoga and mindfulness tutor": {'name': ['yoga', 'and', 'mindfulness', 'tutor']},
  "speech and language tutor": {'name': ['speech', 'and', 'language', 'tutor']},
  "robotics education tutor": {'name': ['robotics', 'education', 'tutor']},
  "music theory tutor": {'name': ['music', 'theory', 'tutor']},
  "drama and theater arts tutor": {'name': ['drama', 'and', 'theater', 'arts', 'tutor']},
  "nutrition education tutor": {'name': ['nutrition', 'education', 'tutor']},
  "coding for kids tutor": {'name': ['coding', 'for', 'kids', 'tutor']},
  "environmental science tutor": {'name': ['environmental', 'science', 'tutor']},
  "financial literacy for teens tutor": {'name': ['financial', 'literacy', 'for', 'teens', 'tutor']},
  "art history tutor": {'name': ['art', 'history', 'tutor']},
  "graphic design tutor": {'name': ['graphic', 'design', 'tutor']},
  "film studies tutor": {'name': ['film', 'studies', 'tutor']},
  "spanish language tutor": {'name': ['spanish', 'language', 'tutor']},
  "coding for teens tutor": {'name': ['coding', 'for', 'teens', 'tutor']},
  "astronomy education tutor": {'name': ['astronomy', 'education', 'tutor']},
  "chess instruction tutor": {'name': ['chess', 'instruction', 'tutor']},
  "engineering concepts tutor": {'name': ['engineering', 'concepts', 'tutor']},
  "interior design tutor": {'name': ['interior', 'design', 'tutor']},
  "digital literacy tutor": {'name': ['digital', 'literacy', 'tutor']},
  "journalism tutor": {'name': ['journalism', 'tutor']},
  "earth science tutor": {'name': ['earth', 'science', 'tutor']},
  "drama therapy tutor": {'name': ['drama', 'therapy', 'tutor']},
  "personal development tutor": {'name': ['personal', 'development', 'tutor']},
  "chess strategies tutor": {'name': ['chess', 'strategies', 'tutor']},
  "culinary arts tutor": {'name': ['culinary', 'arts', 'tutor']},
  "cybersecurity tutor": {'name': ['cybersecurity', 'tutor']},
  "renewable energy tutor": {'name': ['renewable', 'energy', 'tutor']},
  "video production tutor": {'name': ['video', 'production', 'tutor']},
  "sustainable living tutor": {'name': ['sustainable', 'living', 'tutor']},
  "public speaking tutor": {'name': ['public', 'speaking', 'tutor']},
  "robotics engineering tutor": {'name': ['robotics', 'engineering', 'tutor']},
  "podcast production tutor": {'name': ['podcast', 'production', 'tutor']},
  "3d printing tutor": {'name': ['3d', 'printing', 'tutor']},
  "astronomy outreach tutor": {'name': ['astronomy', 'outreach', 'tutor']},
  "social media marketing tutor": {'name': ['social', 'media', 'marketing', 'tutor']},
  "e-learning instruction tutor": {'name': ['e-learning', 'instruction', 'tutor']},
  "sustainable fashion tutor": {'name': ['sustainable', 'fashion', 'tutor']},
  "game design tutor": {'name': ['game', 'design', 'tutor']},
  "health informatics tutor": {'name': ['health', 'informatics', 'tutor']},
  "language translation tutor": {'name': ['language', 'translation', 'tutor']},
  "data science tutor": {'name': ['data', 'science', 'tutor']},
  "augmented reality tutor": {'name': ['augmented', 'reality', 'tutor']},
  "receptionist": {'name': ['receptionist']},
  "hotel front office rep": {'name': ['hotel', 'front', 'office', 'rep']},
  "guest services associate": {'name': ['guest', 'services', 'associate']},
  "front office specialist": {'name': ['front', 'office', 'specialist']},
  "front desk agent": {'name': ['front', 'desk', 'agent']},
  "guest relations officer": {'name': ['guest', 'relations', 'officer']},
  "hotel receptionist": {'name': ['hotel', 'receptionist']},
  "guest service representative": {'name': ['guest', 'service', 'representative']},
  "hotel concierge": {'name': ['hotel', 'concierge']},
  "reservation specialist": {'name': ['reservation', 'specialist']},
  "front desk specialist": {'name': ['front', 'desk', 'specialist']},
  "front office representative": {'name': ['front', 'office', 'representative']},
  "events coordinator": {'name': ['events', 'coordinator']},
  "guest relations specialist": {'name': ['guest', 'relations', 'specialist']},
  "concierge": {'name': ['concierge']},
  "reservation agent": {'name': ['reservation', 'agent']},
  "sales coordinator": {'name': ['sales', 'coordinator']},
  "catering coordinator": {'name': ['catering', 'coordinator']},
  "event sales manager": {'name': ['event', 'sales', 'manager']},
  "sales manager": {'name': ['sales', 'manager']},
  "spa therapist": {'name': ['spa', 'therapist']},
  "it support specialist": {'name': ['it', 'support', 'specialist']},
  "fitness instructor": {'name': ['fitness', 'instructor']},
  "executive chef": {'name': ['executive', 'chef']},
  "hr specialist": {'name': ['hr', 'specialist']},
  "project manager": {'name': ['project', 'manager']},
  "public relations specialist": {'name': ['public', 'relations', 'specialist']},
  "head bartender": {'name': ['head', 'bartender']},
  "hotel sales manager": {'name': ['hotel', 'sales', 'manager']},
  "pastry chef": {'name': ['pastry', 'chef']},
  "restaurant supervisor": {'name': ['restaurant', 'supervisor']},
  "barista": {'name': ['barista']},
  "executive housekeeper": {'name': ['executive', 'housekeeper']},
  "banquet chef": {'name': ['banquet', 'chef']},
  "restaurant bartender": {'name': ['restaurant', 'bartender']},
  "restaurant host": {'name': ['restaurant', 'host']},
  "room attendant": {'name': ['room', 'attendant']},
  "restaurant manager": {'name': ['restaurant', 'manager']},
  "bar supervisor": {'name': ['bar', 'supervisor']},
  "banquet server": {'name': ['banquet', 'server']},
  "kitchen steward": {'name': ['kitchen', 'steward']},
  "coffee barista": {'name': ['coffee', 'barista']},
  "sous chef": {'name': ['sous', 'chef']},
  "hotel sales executive": {'name': ['hotel', 'sales', 'executive']},
  "restaurant chef": {'name': ['restaurant', 'chef']},
  "hotel financial analyst": {'name': ['hotel', 'financial', 'analyst']},
  "restaurant server": {'name': ['restaurant', 'server']},
  "hotel it support specialist": {'name': ['hotel', 'it', 'support', 'specialist']},
  "hotel front office assistant": {'name': ['hotel', 'front', 'office', 'assistant']},
  "restaurant expeditor": {'name': ['restaurant', 'expeditor']},
  "cook": {'name': ['buffet', 'line', 'cook']},
  "lead cook": {'name': ['lead', 'cook']},
  "head chef": {'name': ['head', 'chef']},
  "sushi chef": {'name': ['sushi', 'chef']},
  "italian chef": {'name': ['italian', 'chef']},
  "mexican chef": {'name': ['mexican', 'chef']},
  "grill chef": {'name': ['grill', 'chef']},
  "mediterranean chef": {'name': ['mediterranean', 'chef']},
  "seafood chef": {'name': ['seafood', 'chef']},
  "vegetable chef": {'name': ['vegetable', 'chef']},
  "vegetarian chef": {'name': ['vegetarian', 'chef']},
  "caribbean chef": {'name': ['caribbean', 'chef']},
  "steakhouse chef": {'name': ['steakhouse', 'chef']},
  "dessert chef": {'name': ['dessert', 'chef']},
  "culinary director": {'name': ['culinary', 'director']},
  "buffet culinary director": {'name': ['buffet', 'culinary', 'director']},
  "culinary specialist": {'name': ['culinary', 'specialist']},
  "culinary researcher": {'name': ['culinary', 'researcher']},
  "culinary operations manager": {'name': ['culinary', 'operations', 'manager']},
  "seafood specialist": {'name': ['seafood', 'specialist']},
  "catering director": {'name': ['catering', 'director']},
  "supervisor": {'name': ['supervisor']},
  "quality assurance specialist": {'name': ['quality', 'assurance', 'specialist']},
  "qa specialist": {'name': ['qa', 'specialist']},
  "development manager": {'name': ['development', 'manager']},
  "innovation manager": {'name': ['innovation', 'manager']},
  "catering manager": {'name': ['catering', 'manager']},
  "catering consultant": {'name': ['catering', 'consultant']},
  "catering supervisor": {'name': ['catering', 'supervisor']},
  "catering specialist": {'name': ['catering', 'specialist']},
  "frontend developer": {'name': ['frontend', 'developer']},
  "full stack developer": {'name': ['full', 'stack', 'developer']},
  "backend developer": {'name': ['backend', 'developer']},
  "app developer": {'name': ['app', 'developer']},
  "database developer": {'name': ['database', 'developer']},
  "frontend architect": {'name': ['frontend', 'architect']},
  "devops engineer": {'name': ['devops', 'engineer']},
  "cybersecurity developer": {'name': ['cybersecurity', 'developer']},
  "cloud solutions architect": {'name': ['cloud', 'solutions', 'architect']},
  "machine learning developer": {'name': ['machine', 'learning', 'developer']},
  "web accessibility specialist": {'name': ['web', 'accessibility', 'specialist']},
  "game developer": {'name': ['game', 'developer']},
  "framework developer": {'name': ['framework', 'developer']},
  "web security consultant": {'name': ['web', 'security', 'consultant']},
  "database specialist": {'name': ['database', 'specialist']},
  "database engineer": {'name': ['database', 'engineer']},
  "database analyst": {'name': ['database', 'analyst']},
  "cloud database manager": {'name': ['cloud', 'database', 'manager']},
  "database architect": {'name': ['database', 'architect']},
  "nosql database specialist": {'name': ['nosql', 'database', 'specialist']},
  "senior database engineer": {'name': ['senior', 'database', 'engineer']},
  "cloud database specialist": {'name': ['cloud', 'database', 'specialist']},
  "nosql database engineer": {'name': ['nosql', 'database', 'engineer']},
  "database security expert": {'name': ['database', 'security', 'expert']},
  "cloud database architect": {'name': ['cloud', 'database', 'architect']},
  "senior database analyst": {'name': ['senior', 'database', 'analyst']},
  "database management consultant": {'name': ['database', 'management', 'consultant']},
  "data security specialist": {'name': ['data', 'security', 'specialist']},
  "systems analyst": {'name': ['systems', 'analyst']},
  "data engineer": {'name': ['data', 'engineer']},
  "cybersecurity analyst": {'name': ['cybersecurity', 'analyst']},
  "senior database administrator": {'name': ['senior', 'database', 'administrator']},
  "database systems architect": {'name': ['database', 'systems', 'architect']},
  "database security analyst": {'name': ['database', 'security', 'analyst']},
  "big data database administrator": {'name': ['big', 'data', 'database', 'administrator']},
  "database performance tuning specialist": {'name': ['database', 'performance', 'tuning', 'specialist']},
  "junior database administrator": {'name': ['junior', 'database', 'administrator']},
  "database replication specialist": {'name': ['database', 'replication', 'specialist']},
  "nosql database administrator": {'name': ['nosql', 'database', 'administrator']},
  "database backup and recovery specialist": {'name': ['database', 'backup', 'and', 'recovery', 'specialist']},
  "remote database administrator": {'name': ['remote', 'database', 'administrator']},
  "database compliance analyst": {'name': ['database', 'compliance', 'analyst']},
  "database automation specialist": {'name': ['database', 'automation', 'specialist']},
  "database change management analyst": {'name': ['database', 'change', 'management', 'analyst']},
  "database innovation specialist": {'name': ['database', 'innovation', 'specialist']},
  "database user experience analyst": {'name': ['database', 'user', 'experience', 'analyst']},
  "database cloud migration specialist": {'name': ['database', 'cloud', 'migration', 'specialist']},
  "database scalability engineer": {'name': ['database', 'scalability', 'engineer']},
  "database devops engineer": {'name': ['database', 'devops', 'engineer']},
  "database ai integration specialist": {'name': ['database', 'ai', 'integration', 'specialist']},
  "blockchain database administrator": {'name': ['blockchain', 'database', 'administrator']},
  "data governance analyst": {'name': ['data', 'governance', 'analyst']},
  "database continuous improvement specialist": {'name': ['database', 'continuous', 'improvement', 'specialist']},
  "database analytics specialist": {'name': ['database', 'analytics', 'specialist']},
  "database compliance and auditing analyst": {'name': ['database', 'compliance', 'and', 'auditing', 'analyst']},
  "database change control specialist": {'name': ['database', 'change', 'control', 'specialist']},
  "database migration engineer": {'name': ['database', 'migration', 'engineer']},
  "remote database support specialist": {'name': ['remote', 'database', 'support', 'specialist']},
  "database data encryption specialist": {'name': ['database', 'data', 'encryption', 'specialist']},
  "database cloud integration specialist": {'name': ['database', 'cloud', 'integration', 'specialist']},
  "database query optimization analyst": {'name': ['database', 'query', 'optimization', 'analyst']},
  "database performance analyst": {'name': ['database', 'performance', 'analyst']},
  "cloud database administrator": {'name': ['cloud', 'database', 'administrator']},
  "database automation engineer": {'name': ['database', 'automation', 'engineer']},
  "database devsecops specialist": {'name': ['database', 'devsecops', 'specialist']},
  "database ai integration engineer": {'name': ['database', 'ai', 'integration', 'engineer']},
  "senior database architect": {'name': ['senior', 'database', 'architect']},
  "remote database optimization specialist": {'name': ['remote', 'database', 'optimization', 'specialist']},
  "database data privacy analyst": {'name': ['database', 'data', 'privacy', 'analyst']},
  "database cloud migration engineer": {'name': ['database', 'cloud', 'migration', 'engineer']},
  "database disaster recovery specialist": {'name': ['database', 'disaster', 'recovery', 'specialist']},
  "database scalability specialist": {'name': ['database', 'scalability', 'specialist']},
  "database security and compliance analyst": {'name': ['database', 'security', 'and', 'compliance', 'analyst']},
  "database ui/ux analyst": {'name': ['database', 'ui/ux', 'analyst']},
  "database machine learning integration specialist": {'name': ['database', 'machine', 'learning', 'integration', 'specialist']},
  "database multi-cloud specialist": {'name': ['database', 'multi-cloud', 'specialist']},
  "database chatbot integration specialist": {'name': ['database', 'chatbot', 'integration', 'specialist']},
  "database cloud security specialist": {'name': ['database', 'cloud', 'security', 'specialist']},
  "database integration architect": {'name': ['database', 'integration', 'architect']},
  "database performance engineer": {'name': ['database', 'performance', 'engineer']},
  "it analyst": {'name': ['it', 'analyst']},
  "software developer": {'name': ['software', 'developer']},
  "systems engineer": {'name': ['systems', 'engineer']},
  "business systems analyst": {'name': ['business', 'systems', 'analyst']},
  "application analyst": {'name': ['application', 'analyst']},
  "it consultant": {'name': ['it', 'consultant']},
  "data analyst": {'name': ['data', 'analyst']},
  "technical support analyst": {'name': ['technical', 'support', 'analyst']},
  "ux/ui designer": {'name': ['ux/ui', 'designer']},
  "network engineer": {'name': ['network', 'engineer']},
  "machine learning engineer": {'name': ['machine', 'learning', 'engineer']},
  "business intelligence analyst": {'name': ['business', 'intelligence', 'analyst']},
  "data scientist": {'name': ['data', 'scientist']},
  "software analyst": {'name': ['software', 'analyst']},
  "it systems analyst": {'name': ['it', 'systems', 'analyst']},
  "technical business analyst": {'name': ['technical', 'business', 'analyst']},
  "it operations analyst": {'name': ['it', 'operations', 'analyst']},
  "it security analyst": {'name': ['it', 'security', 'analyst']},
  "network security engineer": {'name': ['network', 'security', 'engineer']},
  "ai/ml analyst": {'name': ['ai/ml', 'analyst']},
  "erp analyst": {'name': ['erp', 'analyst']},
  "cloud security architect": {'name': ['cloud', 'security', 'architect']},
  "it governance analyst": {'name': ['it', 'governance', 'analyst']},
  "devsecops engineer": {'name': ['devsecops', 'engineer']},
  "it business continuity analyst": {'name': ['it', 'business', 'continuity', 'analyst']},
  "it compliance analyst": {'name': ['it', 'compliance', 'analyst']},
  "it procurement analyst": {'name': ['it', 'procurement', 'analyst']},
  "it change management analyst": {'name': ['it', 'change', 'management', 'analyst']},
  "it data governance analyst": {'name': ['it', 'data', 'governance', 'analyst']},
  "it service delivery analyst": {'name': ['it', 'service', 'delivery', 'analyst']},
  "it asset management analyst": {'name': ['it', 'asset', 'management', 'analyst']},
  "it training and development analyst": {'name': ['it', 'training', 'and', 'development', 'analyst']},
  "it vendor management analyst": {'name': ['it', 'vendor', 'management', 'analyst']},
  "it capacity planning analyst": {'name': ['it', 'capacity', 'planning', 'analyst']},
  "it incident response analyst": {'name': ['it', 'incident', 'response', 'analyst']},
  "it project analyst": {'name': ['it', 'project', 'analyst']},
  "app analyst": {'name': ['app', 'analyst']},
  "business systems integrator": {'name': ['business', 'systems', 'integrator']},
  "it compliance auditor": {'name': ['it', 'compliance', 'auditor']},
  "blockchain analyst": {'name': ['blockchain', 'analyst']},
  "it business analyst": {'name': ['it', 'business', 'analyst']},
  "cloud solutions analyst": {'name': ['cloud', 'solutions', 'analyst']},
  "it risk analyst": {'name': ['it', 'risk', 'analyst']},
  "it architecture analyst": {'name': ['it', 'architecture', 'analyst']},
  "it knowledge management analyst": {'name': ['it', 'knowledge', 'management', 'analyst']},
  "junior system analyst": {'name': ['junior', 'system', 'analyst']},
  "systems support analyst": {'name': ['systems', 'support', 'analyst']},
  "entry-level business analyst": {'name': ['entry-level', 'business', 'analyst']},
  "it intern": {'name': ['it', 'intern']},
  "entry-level systems engineer": {'name': ['entry-level', 'systems', 'engineer']},
  "business analyst": {'name': ['business', 'analyst']},
  "it support technician": {'name': ['it', 'support', 'technician']},
  "technical writer": {'name': ['technical', 'writer']},
  "trainee ux/ui designer": {'name': ['trainee', 'ux/ui', 'designer']},
  "programming intern": {'name': ['programming', 'intern']},
  "entry-level cloud solutions analyst": {'name': ['entry-level', 'cloud', 'solutions', 'analyst']},
  "it support trainee": {'name': ['it', 'support', 'trainee']},
  "it trainee": {'name': ['it', 'trainee']},
  "systems integration intern": {'name': ['systems', 'integration', 'intern']},
  "entry-level it auditor": {'name': ['entry-level', 'it', 'auditor']},
  "mobile app specialist": {'name': ['mobile', 'app', 'specialist']},
  "mobile application specialist": {'name': ['mobile', 'application', 'specialist']},
  "application specialist": {'name': ['application', 'specialist']},
  "mobile app engineer": {'name': ['mobile', 'app', 'engineer']},
  "mobile application engineer": {'name': ['mobile', 'application', 'engineer']},
  "mobile app ux/ui specialist": {'name': ['mobile', 'app', 'ux/ui', 'specialist']},
  "ux/ui specialist": {'name': ['ux/ui', 'specialist']},
  "cybersecurity specialist": {'name': ['cybersecurity', 'specialist']},
  "mobile app ai specialist": {'name': ['mobile', 'app', 'ai', 'specialist']},
  "ai specialist": {'name': ['ai', 'specialist']},
  "artificial intelligence specialist": {'name': ['artificial', 'intelligence', 'specialist']},
  "security engineer": {'name': ['security', 'engineer']},
  "security developer": {'name': ['security', 'developer']},
  "ai developer": {'name': ['ai', 'developer']},
  "artificial intelligence developer": {'name': ['artificial', 'intelligence', 'developer']},
  "ux researcher": {'name': ['ux', 'researcher']},
  "ui/ux researcher": {'name': ['ui/ux', 'researcher']},
  "ux/ui researcher": {'name': ['ux/ui', 'researcher']},
  "scrum master": {'name': ['scrum', 'master']},
  "game designer": {'name': ['game', 'designer']},
  "ui developer": {'name': ['ui', 'developer']},
  "security analyst": {'name': ['security', 'analyst']},
  "qa engineer": {'name': ['qa', 'engineer']},
  "ai research scientist": {'name': ['ai', 'research', 'scientist']},
  "embedded systems engineer": {'name': ['embedded', 'systems', 'engineer']},
  "robotics engineer": {'name': ['robotics', 'engineer']},
  "gis analyst": {'name': ['gis', 'analyst']},
  "software development engineer in test (sdet)": {'name': ['software', 'development', 'engineer', 'in', 'test', '(sdet)']},
  "cloud solutions engineer": {'name': ['cloud', 'solutions', 'engineer']},
  "security software engineer": {'name': ['security', 'software', 'engineer']},
  "ux/ui software engineer": {'name': ['ux/ui', 'software', 'engineer']},
  "software architect": {'name': ['software', 'architect']},
  "natural language processing (nlp) engineer": {'name': ['natural', 'language', 'processing', '(nlp)', 'engineer']},
  "cybersecurity software engineer": {'name': ['cybersecurity', 'software', 'engineer']},
  "robotics software engineer": {'name': ['robotics', 'software', 'engineer']},
  "cloud security engineer": {'name': ['cloud', 'security', 'engineer']},
  "ai/ml operations engineer": {'name': ['ai/ml', 'operations', 'engineer']},
  "phlebotomist": {'name': ['phlebotomist']},
  "medical scribe": {'name': ['medical', 'scribe']},
  "medical billing specialist": {'name': ['medical', 'billing', 'specialist']},
  "medical assistant intern": {'name': ['medical', 'assistant', 'intern']},
  "certified nursing assistant (cna)": {'name': ['certified', 'nursing', 'assistant', '(cna)']},
  "healthcare administrative assistant": {'name': ['healthcare', 'administrative', 'assistant']},
  "medical interpreter": {'name': ['medical', 'interpreter']},
  "pharmacy technician": {'name': ['pharmacy', 'technician']},
  "health educator": {'name': ['health', 'educator']},
  "rehabilitation aide": {'name': ['rehabilitation', 'aide']},
  "radiologic technologist": {'name': ['radiologic', 'technologist']},
  "medical equipment technician": {'name': ['medical', 'equipment', 'technician']},
  "patient services representative": {'name': ['patient', 'services', 'representative']},
  "occupational therapy assistant": {'name': ['occupational', 'therapy', 'assistant']},
  "surgical technologist": {'name': ['surgical', 'technologist']},
  "medical receptionist": {'name': ['medical', 'receptionist']},
  "cardiac sonographer": {'name': ['cardiac', 'sonographer']},
  "healthcare data analyst": {'name': ['healthcare', 'data', 'analyst']},
  "community health worker": {'name': ['community', 'health', 'worker']},
  "neurodiagnostic technologist": {'name': ['neurodiagnostic', 'technologist']},
  "hospital administrator": {'name': ['hospital', 'administrator']},
  "chiropractic assistant": {'name': ['chiropractic', 'assistant']},
  "healthcare compliance officer": {'name': ['healthcare', 'compliance', 'officer']},
  "dental assistant": {'name': ['dental', 'assistant']},
  "healthcare consultant": {'name': ['healthcare', 'consultant']},
  "medical transcriptionist": {'name': ['medical', 'transcriptionist']},
  "genetic counselor": {'name': ['genetic', 'counselor']},
  "home health aide": {'name': ['home', 'health', 'aide']},
  "healthcare it specialist": {'name': ['healthcare', 'it', 'specialist']},
  "optometric technician": {'name': ['optometric', 'technician']},
  "manager": {'name': ['manager']},
  "medical equipment sales representative": {'name': ['medical', 'equipment', 'sales', 'representative']},
  "acupuncturist": {'name': ['acupuncturist']},
  "hospice nurse": {'name': ['hospice', 'nurse']},
  "healthcare social worker": {'name': ['healthcare', 'social', 'worker']},
  "medical equipment repair technician": {'name': ['medical', 'equipment', 'repair', 'technician']},
  "occupational therapist": {'name': ['occupational', 'therapist']},
  "medical coding specialist": {'name': ['medical', 'coding', 'specialist']},
  "physical therapist": {'name': ['physical', 'therapist']},
  "healthcare marketing specialist": {'name': ['healthcare', 'marketing', 'specialist']},
  "dietitian": {'name': ['dietitian']},
  "health information technician": {'name': ['health', 'information', 'technician']},
  "medical office assistant": {'name': ['medical', 'office', 'assistant']},
  "clinical data analyst": {'name': ['clinical', 'data', 'analyst']},
  "medical laboratory assistant": {'name': ['medical', 'laboratory', 'assistant']},
  "home care nurse": {'name': ['home', 'care', 'nurse']},
  "healthcare receptionist": {'name': ['healthcare', 'receptionist']},
  "medical sales representative": {'name': ['medical', 'sales', 'representative']},
  "art therapist": {'name': ['art', 'therapist']},
  "healthcare quality analyst": {'name': ['healthcare', 'quality', 'analyst']},
  "nurse educator": {'name': ['nurse', 'educator']},
  "medical claims processor": {'name': ['medical', 'claims', 'processor']},
  "cardiovascular technologist": {'name': ['cardiovascular', 'technologist']},
  "dental hygienist": {'name': ['dental', 'hygienist']},
  "respiratory therapist": {'name': ['respiratory', 'therapist']},
  "medical collections specialist": {'name': ['medical', 'collections', 'specialist']},
  "mental health counselor": {'name': ['mental', 'health', 'counselor']},
  "physical therapy assistant": {'name': ['physical', 'therapy', 'assistant']},
  "healthcare customer service representative": {'name': ['healthcare', 'customer', 'service', 'representative']},
  "medical imaging technologist": {'name': ['medical', 'imaging', 'technologist']},
  "orthopedic surgeon": {'name': ['orthopedic', 'surgeon']},
  "healthcare it support specialist": {'name': ['healthcare', 'it', 'support', 'specialist']},
  "speech-language pathologist": {'name': ['speech-language', 'pathologist']},
  "psychiatric nurse practitioner": {'name': ['psychiatric', 'nurse', 'practitioner']},
  "infection control nurse": {'name': ['infection', 'control', 'nurse']},
  "medical ethics consultant": {'name': ['medical', 'ethics', 'consultant']},
  "podiatrist": {'name': ['podiatrist']},
  "anesthesiologist": {'name': ['anesthesiologist']},
  "nutritionist": {'name': ['nutritionist']},
  "healthcare technology analyst": {'name': ['healthcare', 'technology', 'analyst']},
  "neonatal nurse": {'name': ['neonatal', 'nurse']},
  "healthcare equipment procurement specialist": {'name': ['healthcare', 'equipment', 'procurement', 'specialist']},
  "medical resident": {'name': ['medical', 'resident']},
  "senior physician": {'name': ['senior', 'physician']},
  "er physician": {'name': ['er', 'physician']},
  "general practitioner": {'name': ['general', 'practitioner']},
  "junior surgeon": {'name': ['junior', 'surgeon']},
  "chief medical officer": {'name': ['chief', 'medical', 'officer']},
  "obstetrician": {'name': ['obstetrician']},
  "cardiologist": {'name': ['cardiologist']},
  "junior pediatrician": {'name': ['junior', 'pediatrician']},
  "neonatal nurse practitioner": {'name': ['neonatal', 'nurse', 'practitioner']},
  "gynecologic oncologist": {'name': ['gynecologic', 'oncologist']},
  "urologist": {'name': ['urologist']},
  "junior emergency physician": {'name': ['junior', 'emergency', 'physician']},
  "psychiatrist": {'name': ['psychiatrist']},
  "pediatric surgeon": {'name': ['pediatric', 'surgeon']},
  "gastroenterologist": {'name': ['gastroenterologist']},
  "allergist": {'name': ['allergist']},
  "junior gynecologist": {'name': ['junior', 'gynecologist']},
  "family medicine practitioner": {'name': ['family', 'medicine', 'practitioner']},
  "dermatologist": {'name': ['dermatologist']},
  "plastic surgeon": {'name': ['plastic', 'surgeon']},
  "radiologist": {'name': ['radiologist']},
  "junior neurologist": {'name': ['junior', 'neurologist']},
  "orthodontist": {'name': ['orthodontist']},
  "ophthalmologist": {'name': ['ophthalmologist']},
  "chiropractor": {'name': ['chiropractor']},
  "junior ent specialist": {'name': ['junior', 'ent', 'specialist']},
  "rheumatologist": {'name': ['rheumatologist']},
  "interventional radiologist": {'name': ['interventional', 'radiologist']},
  "junior endocrinologist": {'name': ['junior', 'endocrinologist']},
  "pulmonologist": {'name': ['pulmonologist']},
  "neurosurgeon": {'name': ['neurosurgeon']},
  "chief of surgery": {'name': ['chief', 'of', 'surgery']},
  "medical researcher": {'name': ['medical', 'researcher']},
  "medical surgical nurse": {'name': ['medical', 'surgical', 'nurse']},
  "intensive care unit nurse": {'name': ['intensive', 'care', 'unit', 'nurse']},
  "operating room nurse": {'name': ['operating', 'room', 'nurse']},
  "pediatric nurse": {'name': ['pediatric', 'nurse']},
  "family medicine physician": {'name': ['family', 'medicine', 'physician']},
  "healthcare administrator": {'name': ['healthcare', 'administrator']},
  "medical writer": {'name': ['medical', 'writer']},
  "clinical psychologist": {'name': ['clinical', 'psychologist']},
  "emergency medical technician (emt)": {'name': ['emergency', 'medical', 'technician', '(emt)']},
  "clinical pharmacist": {'name': ['clinical', 'pharmacist']},
  "medical social worker": {'name': ['medical', 'social', 'worker']},
  "medical librarian": {'name': ['medical', 'librarian']},
  "patient advocate": {'name': ['patient', 'advocate']},
  "sleep technologist": {'name': ['sleep', 'technologist']},
  "medical coder": {'name': ['medical', 'coder']},
  "massage therapist": {'name': ['massage', 'therapist']},
  "optometrist": {'name': ['optometrist']},
  "medical biller": {'name': ['medical', 'biller']},
  "public health analyst": {'name': ['public', 'health', 'analyst']},
  "icu nurse": {'name': ['icu', 'nurse']},
  "medical-surgical nurse": {'name': ['medical-surgical', 'nurse']},
  "pharmacy intern": {'name': ['pharmacy', 'intern']},
  "pharmacy director": {'name': ['pharmacy', 'director']},
  "pharmacy assistant": {'name': ['pharmacy', 'assistant']},
  "compounding pharmacist": {'name': ['compounding', 'pharmacist']},
  "pharmacy technician trainee": {'name': ['pharmacy', 'technician', 'trainee']},
  "pharmacy consultant": {'name': ['pharmacy', 'consultant']},
  "pharmaceutical researcher": {'name': ['pharmaceutical', 'researcher']},
  "pharmacy compliance officer": {'name': ['pharmacy', 'compliance', 'officer']},
  "antimicrobial stewardship pharmacist": {'name': ['antimicrobial', 'stewardship', 'pharmacist']},
  "lab technician": {'name': ['lab', 'technician']},
  "senior lab technologist": {'name': ['senior', 'lab', 'technologist']},
  "medical technologist": {'name': ['medical', 'technologist']},
  "clinical lab scientist": {'name': ['clinical', 'lab', 'scientist']},
  "lab supervisor": {'name': ['lab', 'supervisor']},
  "lead medical technologist": {'name': ['lead', 'medical', 'technologist']},
  "lab assistant": {'name': ['lab', 'assistant']},
  "research lab technician": {'name': ['research', 'lab', 'technician']},
  "lab director": {'name': ['lab', 'director']},
  "cytotechnologist": {'name': ['cytotechnologist']},
  "histotechnologist": {'name': ['histotechnologist']},
  "transfusion medicine specialist": {'name': ['transfusion', 'medicine', 'specialist']},
  "genetic lab technologist": {'name': ['genetic', 'lab', 'technologist']},
  "infectious disease specialist": {'name': ['infectious', 'disease', 'specialist']},
  "lab compliance officer": {'name': ['lab', 'compliance', 'officer']},
  "public health lab scientist": {'name': ['public', 'health', 'lab', 'scientist']},
  "microbiologist": {'name': ['microbiologist']},
  "lab operations manager": {'name': ['lab', 'operations', 'manager']},
  "lab billing specialist": {'name': ['lab', 'billing', 'specialist']},
  "lab facilities manager": {'name': ['lab', 'facilities', 'manager']},
  "facilities manager": {'name': ['facilities', 'manager']},
  "lab instrumentation specialist": {'name': ['lab', 'instrumentation', 'specialist']},
  "toxicology lab scientist": {'name': ['toxicology', 'lab', 'scientist']},
  "lab automation specialist": {'name': ['lab', 'automation', 'specialist']},
  "cardiovascular lab technologist": {'name': ['cardiovascular', 'lab', 'technologist']},
  "lab equipment sales representative": {'name': ['lab', 'equipment', 'sales', 'representative']},
  "lab data analyst": {'name': ['lab', 'data', 'analyst']},
  "molecular diagnostics scientist": {'name': ['molecular', 'diagnostics', 'scientist']},
  "lab it support specialist": {'name': ['lab', 'it', 'support', 'specialist']},
  "quality manager": {'name': ['quality', 'manager']},
  "lab supply chain specialist": {'name': ['lab', 'supply', 'chain', 'specialist']},
  "lab safety officer": {'name': ['lab', 'safety', 'officer']},
  "lab public relations specialist": {'name': ['lab', 'public', 'relations', 'specialist']},
  "lab artificial intelligence specialist": {'name': ['lab', 'artificial', 'intelligence', 'specialist']},
  "lab robotics engineer": {'name': ['lab', 'robotics', 'engineer']},
  "teacher's assistant": {'name': ["teacher's", 'assistant']},
  "teacher": {'name': ['teacher']},
  "sped teacher": {'name': ['certified', 'sped', 'teacher']},
  "pe teacher": {'name': ['pe', 'teacher']},
  "special education teacher": {'name': ['special', 'education', 'teacher']},
  "kindergarten teacher": {'name': ['kindergarten', 'teacher']},
  "english teacher": {'name': ['english', 'teacher']},
  "school psychologist": {'name': ['school', 'psychologist']},
  "school counselor": {'name': ['school', 'counselor']},
  "physical education teacher": {'name': ['physical', 'education', 'teacher']},
  "ai researcher": {'name': ['ai', 'researcher']},
  "assistant researcher": {'name': ['assistant', 'researcher']},
  "product owner": {'name': ['product', 'owner']},
  "academic tutor": {'name': ['academic', 'tutor']},
  "associate producer": {'name': ['associate', 'producer']},
  "proofreader": {'name': ['proofreader']},
  "contributor": {'name': ['contributor']},
  "web editor": {'name': ['web', 'editor']},
  "program coordinator": {'name': ['program', 'coordinator']},
  "masters in journalism": {'name': ['masters', 'in', 'journalism']},
  "ux designer": {'name': ['ux', 'designer']},
  "senior ux researcher": {'name': ['senior', 'ux', 'researcher']},
  "design researcher": {'name': ['design', 'researcher']},
  "field researcher": {'name': ['field', 'researcher']},
  "clinical researcher": {'name': ['clinical', 'researcher']},
  "policy analyst": {'name': ['policy', 'analyst']},
  "researcher": {'name': ['researcher']},
  "wildlife biologist": {'name': ['wildlife', 'biologist']},
  "market researcher": {'name': ['market', 'researcher']},
  "linguistics researcher": {'name': ['linguistics', 'researcher']},
  "economic researcher": {'name': ['economic', 'researcher']},
  "renewable energy researcher": {'name': ['renewable', 'energy', 'researcher']},
  "astrophysics researcher": {'name': ['astrophysics', 'researcher']},
  "social science researcher": {'name': ['social', 'science', 'researcher']},
  "cognitive psychology researcher": {'name': ['cognitive', 'psychology', 'researcher']},
  "psychology researcher": {'name': ['psychology', 'researcher']},
  "clinical research scientist": {'name': ['clinical', 'research', 'scientist']},
  "environmental data analyst": {'name': ['environmental', 'data', 'analyst']},
  "behavioral psychology researcher": {'name': ['behavioral', 'psychology', 'researcher']},
  "cybersecurity researcher": {'name': ['cybersecurity', 'researcher']},
  "renewable energy engineer": {'name': ['renewable', 'energy', 'engineer']},
  "biomedical research scientist": {'name': ['biomedical', 'research', 'scientist']},
  "machine learning researcher": {'name': ['machine', 'learning', 'researcher']},
  "climate change analyst": {'name': ['climate', 'change', 'analyst']},
  "cognitive neuroscientist": {'name': ['cognitive', 'neuroscientist']},
  "artificial intelligence researcher": {'name': ['artificial', 'intelligence', 'researcher']},
  "content writer": {'name': ['content', 'writer']},
  "data researcher": {'name': ['data', 'researcher']},
  "environmental scientist": {'name': ['environmental', 'scientist']},
  "political science researcher": {'name': ['political', 'science', 'researcher']},
  "quantum physics researcher": {'name': ['quantum', 'physics', 'researcher']},
  "economics lecturer": {'name': ['economics', 'lecturer']},
  "literature professor": {'name': ['literature', 'professor']},
  "chemistry professor": {'name': ['chemistry', 'professor']},
  "finance instructor": {'name': ['finance', 'instructor']},
  "political science educator": {'name': ['political', 'science', 'educator']},
  "physics professor": {'name': ['physics', 'professor']},
  "marketing professor": {'name': ['marketing', 'professor']},
  "psychology lecturer": {'name': ['psychology', 'lecturer']},
  "history educator": {'name': ['history', 'educator']},
  "computer engineering professor": {'name': ['computer', 'engineering', 'professor']},
  "biology professor": {'name': ['biology', 'professor']},
  "statistics lecturer": {'name': ['statistics', 'lecturer']},
  "engineering professor": {'name': ['engineering', 'professor']},
  "philosophy professor": {'name': ['philosophy', 'professor']},
  "environmental science educator": {'name': ['environmental', 'science', 'educator']},
  "mathematics professor": {'name': ['mathematics', 'professor']},
  "art history professor": {'name': ['art', 'history', 'professor']},
  "sociology lecturer": {'name': ['sociology', 'lecturer']},
  "electrical engineering professor": {'name': ['electrical', 'engineering', 'professor']},
  "foreign language professor": {'name': ['foreign', 'language', 'professor']},
  "anthropology professor": {'name': ['anthropology', 'professor']},
  "music theory instructor": {'name': ['music', 'theory', 'instructor']},
  "business management professor": {'name': ['business', 'management', 'professor']},
  "assistant professor of pharmacology": {'name': ['assistant', 'professor', 'of', 'pharmacology']},
  "adjunct professor of art and design": {'name': ['adjunct', 'professor', 'of', 'art', 'and', 'design']},
  "microbiology professor": {'name': ['microbiology', 'professor']},
  "marketing lecturer": {'name': ['marketing', 'lecturer']},
  "literature instructor": {'name': ['literature', 'instructor']},
  "physics educator": {'name': ['physics', 'educator']},
  "finance professor": {'name': ['finance', 'professor']},
  "political science professor": {'name': ['political', 'science', 'professor']},
  "computer science educator": {'name': ['computer', 'science', 'educator']},
  "environmental science professor": {'name': ['environmental', 'science', 'professor']},
  "psychology professor": {'name': ['psychology', 'professor']},
  "history lecturer": {'name': ['history', 'lecturer']},
  "civil engineering professor": {'name': ['civil', 'engineering', 'professor']},
  "genetics professor": {'name': ['genetics', 'professor']},
  "data science instructor": {'name': ['data', 'science', 'instructor']},
  "philosophy educator": {'name': ['philosophy', 'educator']},
  "renewable energy professor": {'name': ['renewable', 'energy', 'professor']},
  "art history educator": {'name': ['art', 'history', 'educator']},
  "sociology professor": {'name': ['sociology', 'professor']},
  "electrical engineering instructor": {'name': ['electrical', 'engineering', 'instructor']},
  "linguistics professor": {'name': ['linguistics', 'professor']},
  "cultural anthropology professor": {'name': ['cultural', 'anthropology', 'professor']},
  "music theory lecturer": {'name': ['music', 'theory', 'lecturer']},
  "business strategy professor": {'name': ['business', 'strategy', 'professor']},
  "retina surgeon": {'name': ['retina', 'surgeon']},
  "associate professor, director, chairman": {'name': ['associate', 'professor', 'director', 'chairman']},
  "hr & administrative officer": {'name': ['hr', '&', 'administrative', 'officer']},
  "lecturer": {'name': ['lecturer']},
  "assistant professor": {'name': ['assistant', 'professor']},
  "associate professor": {'name': ['associate', 'professor']},
  "professor": {'name': ['professor']},
  "medical anthropology professor": {'name': ['medical', 'anthropology', 'professor']},
  "jazz music professor": {'name': ['jazz', 'music', 'professor']},
  "entrepreneurship professor": {'name': ['entrepreneurship', 'professor']},
  "economics professor": {'name': ['economics', 'professor']},
  "accounting professor": {'name': ['accounting', 'professor']},
  "human resources professor": {'name': ['human', 'resources', 'professor']},
  "information systems professor": {'name': ['information', 'systems', 'professor']},
  "english literature professor": {'name': ['english', 'literature', 'professor']},
  "history professor": {'name': ['history', 'professor']},
  "nursing professor": {'name': ['nursing', 'professor']},
  "computer science professor": {'name': ['computer', 'science', 'professor']},
  "admin recruiter": {'name': ['admin', 'recruiter']},
  "hr officer recruiter": {'name': ['hr', 'officer', 'recruiter']},
  "senior technical corporate recruiter": {'name': ['senior', 'technical', 'corporate', 'recruiter']},
  "talent acquisition specialist": {'name': ['talent', 'acquisition', 'specialist']},
  "recruitment officer": {'name': ['recruitment', 'officer']},
  "recruiting specialist": {'name': ['recruiting', 'specialist']},
  "hr assistant": {'name': ['hr', 'assistant']},
  "recruitment specialist": {'name': ['recruitment', 'specialist']},
  "senior recruitment officer 2": {'name': ['senior', 'recruitment', 'officer', '2']},
  "it recruitment specialist": {'name': ['it', 'recruitment', 'specialist']},
  "senior recruiter": {'name': ['senior', 'recruiter']},
  "recruitment consultant": {'name': ['recruitment', 'consultant']},
  "technical recruiter": {'name': ['technical', 'recruiter']},
  "production recruiter": {'name': ['production', 'recruiter']},
  "management recruiter": {'name': ['management', 'recruiter']},
  "senior technical recruiter": {'name': ['senior', 'technical', 'recruiter']},
  "talent acquisition consultant": {'name': ['talent', 'acquisition', 'consultant']},
  "talent acquisition advisor": {'name': ['talent', 'acquisition', 'advisor']},
  "lead engineering recruiter": {'name': ['lead', 'engineering', 'recruiter']},
  "it recruiter": {'name': ['it', 'recruiter']},
  "executive recruiter": {'name': ['executive', 'recruiter']},
  "corporate recruiter": {'name': ['corporate', 'recruiter']},
  "talent acquisition": {'name': ['talent', 'acquisition']},
  "senior executive recruiter": {'name': ['senior', 'executive', 'recruiter']},
  "talent acquisition recruiter": {'name': ['talent', 'acquisition', 'recruiter']},
  "recruiting manager": {'name': ['recruiting', 'manager']},
  "talent acquisition manager": {'name': ['talent', 'acquisition', 'manager']},
  "sourcer": {'name': ['sourcer']},
  "talent acquisition intern": {'name': ['talent', 'acquisition', 'intern']},
  "campus recruiter": {'name': ['campus', 'recruiter']},
  "staffing specialist": {'name': ['staffing', 'specialist']},
  "recruitment team lead": {'name': ['recruitment', 'team', 'lead']},
  "junior recruiter": {'name': ['junior', 'recruiter']},
  "entry-level recruiter": {'name': ['entry-level', 'recruiter']},
  "human resource officer": {'name': ['human', 'resource', 'officer']},
  "human resource manager": {'name': ['human', 'resource', 'manager']},
  "human resources manager": {'name': ['human', 'resources', 'manager']},
  "senior hr generalist": {'name': ['senior', 'hr', 'generalist']},
  "hr coordinator": {'name': ['hr', 'coordinator']},
  "assistant manager": {'name': ['assistant', 'manager']},
  "sales professional": {'name': ['sales', 'professional']},
  "hr generalist": {'name': ['hr', 'generalist']},
  "administrative services specialist": {'name': ['administrative', 'services', 'specialist']},
  "sr. human resource specialist": {'name': ['sr.', 'human', 'resource', 'specialist']},
  "hr data entry": {'name': ['hr', 'data', 'entry']},
  "hr executive": {'name': ['hr', 'executive']},
  "recruitment manager": {'name': ['recruitment', 'manager']},
  "employee engagement specialist": {'name': ['employee', 'engagement', 'specialist']},
  "hr operations manager": {'name': ['hr', 'operations', 'manager']},
  "compensation and benefits specialist": {'name': ['compensation', 'and', 'benefits', 'specialist']},
  "hr business partner": {'name': ['hr', 'business', 'partner']},
  "recruitment coordinator": {'name': ['recruitment', 'coordinator']},
  "hris specialist": {'name': ['hris', 'specialist']},
  "employee relations manager": {'name': ['employee', 'relations', 'manager']},
  "talent management specialist": {'name': ['talent', 'management', 'specialist']},
  "hr consultant": {'name': ['hr', 'consultant']},
  "employee development specialist": {'name': ['employee', 'development', 'specialist']},
  "employee relations specialist": {'name': ['employee', 'relations', 'specialist']},
  "hr compliance specialist": {'name': ['hr', 'compliance', 'specialist']},
  "hr technology specialist": {'name': ['hr', 'technology', 'specialist']},
  "labor relations specialist": {'name': ['labor', 'relations', 'specialist']},
  "hr data analyst": {'name': ['hr', 'data', 'analyst']},
  "training & development specialist": {'name': ['training', '&', 'development', 'specialist']},
  "hr communications specialist": {'name': ['hr', 'communications', 'specialist']},
  "hr audit & compliance specialist": {'name': ['hr', 'audit', '&', 'compliance', 'specialist']},
  "hr benefits specialist": {'name': ['hr', 'benefits', 'specialist']},
  "hr budget & finance specialist": {'name': ['hr', 'budget', '&', 'finance', 'specialist']},
  "compensation analyst": {'name': ['compensation', 'analyst']},
  "hr change management specialist": {'name': ['hr', 'change', 'management', 'specialist']},
  "hris analyst": {'name': ['hris', 'analyst']},
  "hr legal specialist": {'name': ['hr', 'legal', 'specialist']},
  "training specialist": {'name': ['training', 'specialist']},
  "hr analyst": {'name': ['hr', 'analyst']},
  "hr director": {'name': ['hr', 'director']},
  "organizational development specialist": {'name': ['organizational', 'development', 'specialist']},
  "office coordinator": {'name': ['office', 'coordinator']},
  "administrative manager": {'name': ['administrative', 'manager']},
  "executive assistant": {'name': ['executive', 'assistant']},
  "operations supervisor": {'name': ['operations', 'supervisor']},
  "administrative officer": {'name': ['administrative', 'officer']},
  "office administrator": {'name': ['office', 'administrator']},
  "administrative coordinator": {'name': ['administrative', 'coordinator']},
  "executive secretary": {'name': ['executive', 'secretary']},
  "office assistant": {'name': ['office', 'assistant']},
  "social media manager": {'name': ['social', 'media', 'manager']},
  "logistics specialist": {'name': ['logistics', 'specialist']},
  "communications officer": {'name': ['communications', 'officer']},
  "procurement officer": {'name': ['procurement', 'officer']},
  "market research analyst": {'name': ['market', 'research', 'analyst']},
  "help desk technician": {'name': ['help', 'desk', 'technician']},
  "business advisor": {'name': ['business', 'advisor']},
  "property manager": {'name': ['property', 'manager']},
  "marketing executive": {'name': ['marketing', 'executive']},
  "executive manager": {'name': ['executive', 'manager']},
  "marketing manager": {'name': ['marketing', 'manager']},
  "realtor": {'name': ['realtor']},
  "reporting analyst": {'name': ['reporting', 'analyst']},
  "project support specialist": {'name': ['project', 'support', 'specialist']},
  "office operations coordinator": {'name': ['office', 'operations', 'coordinator']},
  "administrative specialist": {'name': ['administrative', 'specialist']},
  "facilities coordinator": {'name': ['facilities', 'coordinator']},
  "office operations manager": {'name': ['office', 'operations', 'manager']},
  "operational site lead": {'name': ['operational', 'site', 'lead']},
  "business execution administrator": {'name': ['business', 'execution', 'administrator']},
  "account support specialist": {'name': ['account', 'support', 'specialist']},
  "administrative assistant": {'name': ['administrative', 'assistant']},
  "human resource associate partner": {'name': ['human', 'resource', 'associate', 'partner']},
  "sr. quality technician": {'name': ['sr.', 'quality', 'technician']},
  "procurement specialist": {'name': ['procurement', 'specialist']},
  "grant proposal writer": {'name': ['grant', 'proposal', 'writer']},
  "research assistant": {'name': ['research', 'assistant']},
  "project assistant": {'name': ['project', 'assistant']},
  "project analyst": {'name': ['project', 'analyst']},
  "project planner": {'name': ['project', 'planner']},
  "operations coordinator": {'name': ['operations', 'coordinator']},
  "training coordinator": {'name': ['training', 'coordinator']},
  "project specialist": {'name': ['project', 'specialist']},
  "project support analyst": {'name': ['project', 'support', 'analyst']},
  "project implementation specialist": {'name': ['project', 'implementation', 'specialist']},
  "project finance analyst": {'name': ['project', 'finance', 'analyst']},
  "project scheduler": {'name': ['project', 'scheduler']},
  "project researcher": {'name': ['project', 'researcher']},
  "project procurement specialist": {'name': ['project', 'procurement', 'specialist']},
  "project risk management specialist": {'name': ['project', 'risk', 'management', 'specialist']},
  "project stakeholder relations specialist": {'name': ['project', 'stakeholder', 'relations', 'specialist']},
  "service manager": {'name': ['service', 'manager']},
  "clerk": {'name': ['clerk']},
  "retail associate": {'name': ['retail', 'associate']},
  "inventory specialist": {'name': ['inventory', 'specialist']},
  "warehouse associate": {'name': ['warehouse', 'associate']},
  "library assistant": {'name': ['library', 'assistant']},
  "technical support specialist": {'name': ['technical', 'support', 'specialist']},
  "sales associate": {'name': ['sales', 'associate']},
  "human resources assistant": {'name': ['human', 'resources', 'assistant']},
  "data analyst assistant": {'name': ['data', 'analyst', 'assistant']},
  "legal assistant": {'name': ['legal', 'assistant']},
  "maintenance": {'name': ['maintenance']},
  "multimedia content specialist": {'name': ['multimedia', 'content', 'specialist']},
  "communications development specialist": {'name': ['communications', 'development', 'specialist']},
  "marketing campaign specialist": {'name': ['marketing', 'campaign', 'specialist']},
  "creative project specialist": {'name': ['creative', 'project', 'specialist']},
  "brand promotion specialist": {'name': ['brand', 'promotion', 'specialist']},
  "visual arts specialist": {'name': ['visual', 'arts', 'specialist']},
  "communications coordinator": {'name': ['communications', 'coordinator']},
  "content distribution specialist": {'name': ['content', 'distribution', 'specialist']},
  "social media engagement specialist": {'name': ['social', 'media', 'engagement', 'specialist']},
  "graphic design specialist": {'name': ['graphic', 'design', 'specialist']},
  "brand communications specialist": {'name': ['brand', 'communications', 'specialist']},
  "multimedia marketing specialist": {'name': ['multimedia', 'marketing', 'specialist']},
  "pr specialist": {'name': ['pr', 'specialist']},
  "digital media specialist": {'name': ['digital', 'media', 'specialist']},
  "media content specialist": {'name': ['media', 'content', 'specialist']},
  "public affairs specialist": {'name': ['public', 'affairs', 'specialist']},
  "exhibition planning specialist": {'name': ['exhibition', 'planning', 'specialist']},
  "brand development specialist": {'name': ['brand', 'development', 'specialist']},
  "multimedia production specialist": {'name': ['multimedia', 'production', 'specialist']},
  "communications specialist": {'name': ['communications', 'specialist']},
  "content strategist": {'name': ['content', 'strategist']},
  "marketing analytics specialist": {'name': ['marketing', 'analytics', 'specialist']},
  "interactive design specialist": {'name': ['interactive', 'design', 'specialist']},
  "creative director": {'name': ['creative', 'director']},
  "digital marketing specialist": {'name': ['digital', 'marketing', 'specialist']},
  "event promotion specialist": {'name': ['event', 'promotion', 'specialist']},
  "exhibition design specialist": {'name': ['exhibition', 'design', 'specialist']},
  "social media specialist": {'name': ['social', 'media', 'specialist']},
  "copywriter": {'name': ['copywriter']},
  "art director": {'name': ['art', 'director']},
  "video editor": {'name': ['video', 'editor']},
  "exhibit designer": {'name': ['exhibit', 'designer']},
  "exhibition coordinator": {'name': ['exhibition', 'coordinator']},
  "press officer": {'name': ['press', 'officer']},
  "visual merchandiser": {'name': ['visual', 'merchandiser']},
  "user experience designer": {'name': ['user', 'experience', 'designer']},
  "promotions coordinator": {'name': ['promotions', 'coordinator']},
  "copy editor": {'name': ['copy', 'editor']},
  "advertising coordinator": {'name': ['advertising', 'coordinator']},
  "marketing analyst": {'name': ['marketing', 'analyst']},
  "exhibition planner": {'name': ['exhibition', 'planner']},
  "media buyer": {'name': ['media', 'buyer']},
  "press relations officer": {'name': ['press', 'relations', 'officer']},
  "content producer": {'name': ['content', 'producer']},
  "digital media planner": {'name': ['digital', 'media', 'planner']},
  "art curator": {'name': ['art', 'curator']},
  "campaign manager": {'name': ['campaign', 'manager']},
  "media planner": {'name': ['media', 'planner']},
  "exhibition manager": {'name': ['exhibition', 'manager']},
  "public relations coordinator": {'name': ['public', 'relations', 'coordinator']},
  "artistic director": {'name': ['artistic', 'director']},
  "creative strategist": {'name': ['creative', 'strategist']},
  "exhibition designer": {'name': ['exhibition', 'designer']},
  "content creator": {'name': ['content', 'creator']},
  "creative writer": {'name': ['creative', 'writer']},
  "media production manager": {'name': ['media', 'production', 'manager']},
  "production manager": {'name': ['production', 'manager']},
  "multimedia producer": {'name': ['multimedia', 'producer']},
  "pr strategist": {'name': ['pr', 'strategist']},
  "artistic producer": {'name': ['artistic', 'producer']},
  "communications manager": {'name': ['communications', 'manager']},
  "interactive designer": {'name': ['interactive', 'designer']},
  "exhibit coordinator": {'name': ['exhibit', 'coordinator']},
  "community relations specialist": {'name': ['community', 'relations', 'specialist']},
  "multimedia coordinator": {'name': ['multimedia', 'coordinator']},
  "production coordinator": {'name': ['production', 'coordinator']},
  "marketing strategist": {'name': ['marketing', 'strategist']},
  "communications analyst": {'name': ['communications', 'analyst']},
  "media content producer": {'name': ['media', 'content', 'producer']},
  "digital art director": {'name': ['digital', 'art', 'director']},
  "social media analyst": {'name': ['social', 'media', 'analyst']},
  "exhibit manager": {'name': ['exhibit', 'manager']},
  "content marketing specialist": {'name': ['content', 'marketing', 'specialist']},
  "creative development specialist": {'name': ['creative', 'development', 'specialist']},
  "marketing coordinator": {'name': ['marketing', 'coordinator']},
  "interactive media designer": {'name': ['interactive', 'media', 'designer']},
  "visual communication specialist": {'name': ['visual', 'communication', 'specialist']},
  "public affairs analyst": {'name': ['public', 'affairs', 'analyst']},
  "exhibit development specialist": {'name': ['exhibit', 'development', 'specialist']},
  "advertising manager": {'name': ['advertising', 'manager']},
  "digital art producer": {'name': ['digital', 'art', 'producer']},
  "media strategy specialist": {'name': ['media', 'strategy', 'specialist']},
  "multimedia content producer": {'name': ['multimedia', 'content', 'producer']},
  "communications planner": {'name': ['communications', 'planner']},
  "exhibition marketing specialist": {'name': ['exhibition', 'marketing', 'specialist']},
  "public relations analyst": {'name': ['public', 'relations', 'analyst']},
  "creative content specialist": {'name': ['creative', 'content', 'specialist']},
  "visual merchandising specialist": {'name': ['visual', 'merchandising', 'specialist']},
  "public affairs strategist": {'name': ['public', 'affairs', 'strategist']},
  "media planning specialist": {'name': ['media', 'planning', 'specialist']},
}
